/* Local fictional viewer. No site credentials, real records, or network requests. */
const DEMO_KEY='safetywatch-ux-v2';
const caseRoutes=new Set(['case','prep','field','defect','report','preview','share','shared','review','supplement_request','requested','reply','resubmitted','complete','history']);
function canAccessCase(id){return role==='official'?[1,2,3].includes(id):[1,2].includes(id);}
const publicRoutes=new Set(['landing','login','first','public_map','public_building','public_bim']);
const analysisRoutes=new Set(['region','candidate']);
function isAnalysisRoute(route){return analysisRoutes.has(route)&&!(route==='map_model'&&workModel.entry?.workspace==='work');}
const publicBuildings=[
 {id:1,name:'예시 중앙상가',dong:'가동',address:'예시시 중앙로 10',use:'근린생활시설',floors:3,year:1994,model:true,x:155,y:116},
 {id:2,name:'예시 주민회관',dong:'본동',address:'예시시 안전로 20',use:'주민공동이용시설',floors:2,year:1998,model:true,x:350,y:229},
 {id:3,name:'예시 문화시설',dong:'나동',address:'예시시 문화로 30',use:'문화시설',floors:1,year:1991,model:false,x:546,y:113}
];
let signedIn=false,pendingDestination=null,publicQuery='',publicFilter='전체',publicSelected=2,publicRotation=32,publicZoom=1,publicFloor=0,storageOK=true;
let renderedDraftKey='',deniedCaseId=3;
let activeWorkspace='work',lastWorkView=null,lastAnalysisView=null,restoredLogin=false,restoreTime='',demoProfiles={},formDrafts={};
let analysisFilter='전체',dashboardScope='mine',savedCase=null,loadedStore=null;
try{const raw=localStorage.getItem(DEMO_KEY);if(raw){const d=JSON.parse(raw);if(d.schema===2&&d.profiles&&d.case&&Array.isArray(d.case.events)){loadedStore=d;demoProfiles=d.profiles;formDrafts=d.drafts||{};savedCase=d.case;}}}catch(e){storageOK=false;}
const clone=v=>JSON.parse(JSON.stringify(v));
const shortTime=()=>new Date().toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
function workContext(){return {screen,selected,selectedDefect,listFilter,query,listStatus,fieldMode,role};}
function blankProfile(r){return {scope:'mine',filters:{listFilter:'전체',listStatus:'전체',query:''},recent:{screen:r==='official'?'review':'prep',selected:2,selectedDefect:'F-03',listFilter:'전체',query:'',listStatus:'전체',fieldMode:'항목 기준',role:r},analysis:{screen:'region',filter:'전체'},updated:'이전 작업 예시',visited:false};}
function profile(){if(!demoProfiles[role])demoProfiles[role]=blankProfile(role);return demoProfiles[role];}
function persistDemo(){if(!signedIn)return;const p=profile();p.scope=dashboardScope;p.filters={listFilter,listStatus,query};p.updated=shortTime();p.visited=true;savedCase=clone(state);try{localStorage.setItem(DEMO_KEY,JSON.stringify({schema:2,case:savedCase,profiles:demoProfiles,drafts:formDrafts}));storageOK=true;}catch(e){storageOK=false;}}
function draftKey(route=screen){return `${role}:${selected}:${route}:${route==='defect'?selectedDefect:'general'}:v${state.version}`;}
function rememberDraft(){if(!signedIn||publicRoutes.has(screen))return;const fields={};for(const id of ['opinion','evidence-caption','request-text','reply-text']){const el=document.getElementById(id);if(el&&!el.readOnly)fields[id]=el.value;}if(Object.keys(fields).length)formDrafts[renderedDraftKey||draftKey()]=fields;}
function restoreDraft(){if(!signedIn||publicRoutes.has(screen))return;for(const [id,value] of Object.entries(formDrafts[draftKey()]||{})){const el=document.getElementById(id);if(el&&!el.readOnly)el.value=value;}}
function rememberWork(){if(!signedIn||publicRoutes.has(screen)||screen==='access_unavailable')return;const p=profile();if(isAnalysisRoute(screen)){lastAnalysisView={screen,filter:analysisFilter};p.analysis=clone(lastAnalysisView);}else{lastWorkView=workContext();if(!['home','reports','histories','list','data'].includes(screen))p.recent=clone(lastWorkView);p.filters={listFilter,listStatus,query};}}
function applyWorkContext(c){if(!c)return;selected=c.selected||2;selectedDefect=c.selectedDefect||'F-03';listFilter=c.listFilter||'전체';query=c.query||'';listStatus=c.listStatus||'전체';fieldMode=c.fieldMode||'항목 기준';}
navContext=()=>({...workContext(),publicQuery,publicFilter,publicSelected,publicRotation,publicZoom,publicFloor,analysisFilter,dashboardScope});
function restoreNavigation(c){if(!c){go('landing',{pop:true});return;}if(signedIn&&c.role!==role&&!publicRoutes.has(c.screen)){go('home',{pop:true});return;}applyWorkContext(c);publicQuery=c.publicQuery||'';publicFilter=c.publicFilter||'전체';publicSelected=c.publicSelected||2;publicRotation=c.publicRotation??32;publicZoom=c.publicZoom||1;publicFloor=c.publicFloor||0;analysisFilter=c.analysisFilter||'전체';dashboardScope=c.dashboardScope||dashboardScope;go(c.screen||'landing',{pop:true});}
go=function(route,opts={}){if($('#dialog').open)$('#dialog').close();rememberDraft();rememberWork();if(opts.id)selected=opts.id;if(!signedIn&&!publicRoutes.has(route)){pendingDestination={screen:route,id:selected};route='login';}if(signedIn&&caseRoutes.has(route)&&!canAccessCase(selected)){deniedCaseId=selected;route='access_unavailable';}screen=route;activeWorkspace=isAnalysisRoute(screen)?'analysis':'work';render();if(!opts.pop)history.pushState(navContext(),'',`#${screen}`);window.scrollTo(0,0);$('#app').focus({preventScroll:true});rememberWork();persistDemo();};
pickRole=function(r){role=r;go('login');};
login=function(){const p=profile();restoredLogin=p.visited;restoreTime=p.updated;signedIn=true;state=savedCase?clone(savedCase):initialState(role);dashboardScope=p.scope||'mine';applyWorkContext(p.recent);listFilter=p.filters?.listFilter||'전체';listStatus=p.filters?.listStatus||'전체';query=p.filters?.query||'';lastWorkView={...workContext(),screen:'home'};lastAnalysisView=p.analysis||{screen:'region',filter:'전체'};analysisFilter=lastAnalysisView.filter;const dest=pendingDestination;pendingDestination=null;if(dest){go(dest.screen,{id:dest.id});if(screen!=='access_unavailable')toast('로그인 전 선택한 노후건축물의 업무로 연결했습니다.');}else{go('home');toast(dest?'이 기관의 담당 범위에 포함되지 않아 내 업무를 열었습니다.':restoredLogin?'이전 조회환경을 복원했습니다. 현재 상태와 새 소식도 함께 확인하세요.':'가상 업무 계정으로 시작합니다.');}};
function enterLogin(destination=null){if(signedIn){if(destination)go(destination.screen,{id:destination.id});else go('home');return;}pendingDestination=destination;go('login');}
function logoutDemo(){rememberDraft();rememberWork();persistDemo();signedIn=false;pendingDestination=null;go('landing');toast('가상 계정에서 로그아웃했습니다. 다시 로그인하면 작업을 이어갈 수 있습니다.');}
function continueWork(){const c=profile().recent;applyWorkContext(c);let route=c.screen;if(route==='reply'&&state.phase!=='requested')route='case';if(route==='supplement_request'&&state.phase!=='shared')route='review';go(route);}
function openWorkspace(which){rememberDraft();rememberWork();persistDemo();if(which==='analysis'){const c=profile().analysis||{screen:'region',filter:'전체'};analysisFilter=c.filter||'전체';go(c.screen||'region');}else{const c=lastWorkView||{screen:'home',selected:2};applyWorkContext(c);go(c.screen||'home');}}
switchActor=function(r,route){rememberDraft();rememberWork();persistDemo();role=r;signedIn=true;const p=profile();dashboardScope=p.scope||'mine';lastWorkView={...p.recent};analysisFilter=p.analysis.filter;go(route,{id:2});toast(`${r==='official'?'공무원':'전문기관'} 시안으로 전환했습니다. 같은 점검건·버전을 유지합니다.`);};
resetDemo=function(r='agency'){try{localStorage.removeItem(DEMO_KEY);}catch(e){}signedIn=false;savedCase=null;loadedStore=null;demoProfiles={};formDrafts={};role=r;state=initialState(r);selected=2;selectedDefect='F-03';candidateChoice=false;listFilter='전체';listStatus='전체';query='';publicQuery='';publicFilter='전체';publicSelected=2;pendingDestination=null;analysisFilter='전체';dashboardScope='mine';lastWorkView=null;lastAnalysisView=null;go('landing');};
const renderOriginal=render;
render=function(){renderOriginal();const publicPage=publicRoutes.has(screen);document.body.classList.toggle('public-mode',publicPage);$('#sidebar').style.display=publicPage?'none':'';$('#shell').style.gridTemplateColumns=publicPage?'1fr':'';$('#header').innerHTML=`<button class="brand brandbutton" onclick="returnToStart()">안전워치<small>노후건축물 안전진단 관리</small></button><div class="header-right">${publicPage?`<span class="muted">${signedIn?'공개 정보 열람 중':'지자체·전문기관 업무 지원'}</span>${btn(signedIn?'내 업무로 돌아가기':'업무시스템 로그인',signedIn?"go('home')":(['public_building','public_bim'].includes(screen)?`enterLogin({screen:'case',id:${publicSelected}})`:"enterLogin()"),'mini')}`:`<div class="account"><strong>${role==='official'?'예시시 · 건축안전 담당':'예시 B점검기관 · 점검 담당'}</strong>${role==='official'?'조회범위: 내 담당 / 관할 전체':'조회범위: 내 담당 / 기관 전체'}</div>${btn('로그아웃','logoutDemo()','mini')}`}</div>`;
$('#workspace-tabs').innerHTML=publicPage?'':`<div class="workspace-nav" aria-label="작업 공간"><div>${btn('내 업무',"openWorkspace('work')",activeWorkspace==='work'?'active':'')}${btn('지도 분석',"openWorkspace('analysis')",activeWorkspace==='analysis'?'active':'')}</div>${btn('공개 정보 보기',"openPublicMap()",'text mini')}</div>`;
if(!publicPage&&activeWorkspace==='analysis')$('#sidebar').innerHTML=`<h3>지도 분석</h3>${btn('분포·후보 목록',"go('region')",screen==='region'?'active':'')}${btn('후보의 근거·점검',"go('candidate')",screen==='candidate'?'active':'')}<div class="scope">분석 조건과 업무 화면은 각각 유지됩니다.<br>필요한 점검건을 열어 업무로 이어갈 수 있습니다.</div>`;
else if(!publicPage){const old=$('#sidebar').querySelector('[onclick="go(\'region\')"]');if(old)old.remove();}
if(screen==='login'){const card=$('.logincard');if(card)card.insertAdjacentHTML('afterbegin',pendingDestination?`<div class="notice blue compact-notice">로그인 후 <strong>${publicBuildings.find(b=>b.id===pendingDestination.id)?.name||'선택한 건축물'}</strong> 업무로 연결합니다.</div>`:'');$('.loginintro').innerHTML=`<div class="eyebrow">업무시스템 로그인</div><h1>이전 작업을 이어서,<br>새 업무도 놓치지 않게.</h1><p>소속과 역할에 맞는 내 업무 대시보드에서 시작합니다.</p><ul><li>최근 노후건축물·회차와 조회조건 유지</li><li>새 요청과 일정 변화 함께 확인</li><li>별도 지도 분석 탭으로 이동</li></ul>${btn('공개 노후건축물 정보 보기','openPublicMap()','text')}<p class="muted">공개 정보와 공개용 3D는 로그인 없이 볼 수 있습니다.</p>`;const review=$('.logincard .reviewnote');if(review)review.textContent='시안용 계정입니다. 실제 비밀번호는 입력하지 않습니다.';}
restoreDraft();renderedDraftKey=draftKey();if(screen==='public_bim'&&publicBuilding().model)drawPublicModel();renderViewer();};
function publicBuilding(){return publicBuildings.find(b=>b.id===publicSelected)||publicBuildings[1];}
function normalize(s){return s.replace(/\s/g,'').toLowerCase();}
function publicResults(){return publicBuildings.filter(b=>(!publicQuery||normalize(`${b.name}${b.dong}${b.address}`).includes(normalize(publicQuery)))&&(publicFilter==='전체'||b.model));}
function openPublicMap(){go('public_map');}
function searchPublic(inputId='public-search'){publicQuery=document.getElementById(inputId)?.value.trim()||'';const filter=$('#public-model-filter');if(filter)publicFilter=filter.value;go('public_map');}
function choosePublicBuilding(id){publicSelected=id;publicFloor=0;publicRotation=32;publicZoom=1;go('public_building');}
function publicSearchBox(id='public-search'){return `<form class="public-search" onsubmit="event.preventDefault();searchPublic('${id}')"><label class="sr-only" for="${id}">노후건축물명 또는 주소</label><input id="${id}" value="${esc(publicQuery)}" placeholder="노후건축물명 또는 주소를 입력하세요 · 예: 주민회관"><button class="primary" type="submit">검색</button></form>`;}
function cityMap(rows,publicMode=true){return `<svg viewBox="0 0 720 350" role="img" aria-label="예시시 노후건축물 위치를 보여주는 가상 지도"><rect width="720" height="350" fill="#edf3f6"/><g fill="#dbe5ea" stroke="#c5d4df"><rect x="45" y="40" width="165" height="90" rx="6"/><rect x="290" y="45" width="140" height="75" rx="6"/><rect x="485" y="38" width="130" height="103" rx="6"/><rect x="45" y="210" width="155" height="88" rx="6"/><rect x="310" y="195" width="110" height="96" rx="6"/><rect x="490" y="215" width="150" height="90" rx="6"/></g><path d="M0 164H720M253 0V350M454 0V350" stroke="#fff" stroke-width="24"/><path d="M0 325Q120 294 200 322T400 331T720 320" stroke="#bfddea" stroke-width="18" fill="none"/><g fill="#71899d" font-size="12"><text x="18" y="154">중앙로</text><text x="463" y="183">안전로</text><text x="514" y="32">문화로</text></g>${rows.map(b=>`<g class="map-pin" role="button" tabindex="0" aria-label="${b.name} ${b.dong} 열기" onclick="${publicMode?`choosePublicBuilding(${b.id})`:b.id===2?"go('candidate')":"openCase(3)"}" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();this.dispatchEvent(new MouseEvent('click'));}"><circle cx="${b.x}" cy="${b.y}" r="17" fill="${publicMode?'#2165a4':'#a36b2e'}"/><text x="${b.x}" y="${b.y+5}" text-anchor="middle" fill="white" font-size="14">${b.id}</text><rect x="${b.x-63}" y="${b.y+24}" width="126" height="26" rx="4" fill="white"/><text x="${b.x}" y="${b.y+42}" text-anchor="middle" fill="#304d66" font-size="12">${b.name}</text></g>`).join('')}<text x="15" y="342" fill="#637f91" font-size="11">설명용 가상 지도 · 실제 건물·좌표 아님</text></svg>`;}
pages.landing=()=>`<div class="entry-hero"><div class="eyebrow">안전워치 · 노후건축물 안전진단 관리</div><h1>노후건축물 안전진단 업무,<br>이전 작업부터 이어갑니다.</h1><p>안전진단 관리가 필요하거나 검토가 필요한 노후건축물의 점검·진단 업무를 지원합니다.</p></div><div class="entry-grid"><section class="entry-card work-entry"><span class="entry-icon">▤</span><div class="eyebrow">지자체 공무원 · 전문기관 담당자</div><h2>노후건축물 안전진단 업무</h2><p>담당 점검과 작성 중인 보고서를 이어가고, 새 요청과 기한을 확인하세요.</p><ul><li>내 담당 업무·점검 현황</li><li>현장 근거·보고서·검토 이력</li><li>별도 탭에서 관할·담당 대상 지도 분석</li></ul>${btn(signedIn?'내 업무 대시보드':'업무시스템 로그인',signedIn?"go('home')":"enterLogin()",'primary')}<div class="entry-bottom">업무 로그인 → 개인 작업 대시보드 → 최근 작업 이어가기<br>직전 작업·조회조건을 유지하고 현재 요청도 함께 확인합니다.</div></section><section class="entry-card public-entry"><span class="entry-icon">⌕</span><div class="eyebrow">공개 정보 조회 · 로그인 없이 이용</div><h2>노후건축물 정보조회</h2><p>GIS+sBIM 기반 노후건축물 안전진단 정보조회 서비스</p><p class="muted">시스템에 공개된 기본정보·안전진단 정보와 3D를 지도에서 찾아보세요.</p>${publicSearchBox('entry-search')}<div class="actions">${btn('공개 지도 바로 보기','openPublicMap()')}${btn('예시 주민회관 살펴보기','choosePublicBuilding(2)','text')}</div><div class="entry-bottom">공개 지도 → 노후건축물 공개 정보 → 공개용 3D/BIM</div></section></div><div class="entry-foot"><strong>업무 계정 안내</strong> 업무 기능은 소속과 권한이 확인된 계정으로 이용합니다. 공개된 정보만 조회할 때는 로그인하지 않아도 됩니다.</div>`;
pages.public_map=()=>{const rows=publicResults();return `<div class="bar"><div><div class="eyebrow">공개 노후건축물 정보 · 로그인 없이 조회</div><h1>지도에서 노후건축물 찾기</h1><p class="muted">GIS+sBIM 기반 노후건축물 안전진단 정보조회 · 공개된 자료의 범위에서 확인합니다.</p></div>${btn('서비스 메인',"go('landing')")}</div><section class="panel search-panel">${publicSearchBox()}<div class="public-filter"><label for="public-model-filter">3D 자료</label><select id="public-model-filter" onchange="publicFilter=this.value;go('public_map')"><option ${publicFilter==='전체'?'selected':''}>전체</option><option ${publicFilter!=='전체'?'selected':''}>3D 있음</option></select>${btn('초기화',"publicQuery='';publicFilter='전체';go('public_map')",'text')}<span class="muted">${rows.length}건 · ${publicQuery?esc(publicQuery):'예시시 전체'} · 공개 자료 기준일 2026.09.15</span></div></section><div class="public-map-layout"><section class="panel map-surface">${cityMap(rows)}<div class="map-caption">숫자 표시는 관리 대상·검토 후보 노후건축물의 위치입니다. 안전등급이나 위험도 표시는 아닙니다.</div></section><section class="panel public-results"><h2>같은 조건의 노후건축물 · ${rows.length}건</h2>${rows.length?rows.map(b=>`<button class="public-result" onclick="choosePublicBuilding(${b.id})"><strong>${b.name} · ${b.dong}</strong><span>${b.address}</span><span>${b.use} · 지상 ${b.floors}층</span><span>${chip(b.model?'공개 3D 있음':'3D 자료 미등록',b.model?'blue':'')}</span></button>`).join(''):`<div class="empty"><p>해당 조건의 공개 자료가 없습니다.</p><p>주소를 짧게 입력하거나 3D 조건을 해제해 보세요.</p>${btn('전체 공개 자료 보기',"publicQuery='';publicFilter='전체';go('public_map')")}</div>`}</section></div>`;};
function publicSafetySummary(b){return b.id===2?{record:'2025년 1회차 · 공개 요약 예시',description:'이전 점검 기록이 공개된 경우의 요약 예시입니다. 상세 결함·사진·검토 의견은 업무용 조회에서 확인합니다.'}:{record:'공개 점검 요약 미등록',description:'공개된 점검·진단 요약이 없습니다. 자료 없음은 안전 판정이 아닙니다.'};}
function publicBuildingHead(tab){const b=publicBuilding();return `<div class="breadcrumb">${btn('검색 결과로',"go('public_map')",'text')} / 공개 노후건축물 정보</div><section class="casehead"><div class="bar"><div><div class="eyebrow">공개 자료 · ${b.address}</div><h1>${b.name} · ${b.dong}</h1></div>${chip('로그인 없이 열람','blue')}</div><div class="tabs">${btn('노후건축물 정보',"go('public_building')",tab==='info'?'active':'')}${btn('3D로 건물 보기',"go('public_bim')",tab==='bim'?'active':'')}</div></section>`;}
pages.public_building=()=>{const b=publicBuilding();return publicBuildingHead('info')+`<div class="grid"><section class="panel"><h2>노후건축물 기본정보</h2><dl class="kv"><dt>주소</dt><dd>${b.address}</dd><dt>동 구분</dt><dd>${b.dong}</dd><dt>용도</dt><dd>${b.use}</dd><dt>규모</dt><dd>지상 ${b.floors}층</dd><dt>사용승인 연도</dt><dd>${b.year}년 · 예시</dd><dt>관리·검토 구분</dt><dd>${b.id===3?'검토 후보 · 대상 사유 확인 필요':'점검 관리 대상 · 예시 사업'}</dd></dl><p class="muted">노후 여부와 관리·검토 대상 표시는 위험 판정 또는 법정 안전진단 대상 지정과 구분합니다.</p><div class="source-line">자료 출처: 가상 공개 기본정보 · 기준일 2026.09.15</div><h3>공개 안전정보</h3><p><strong>${publicSafetySummary(b).record}</strong></p><p>${publicSafetySummary(b).description}</p><p class="muted">공개된 기록의 유무를 현재 안전 상태의 판정으로 해석하지 않습니다.</p></section><section class="panel"><h2>3D로 건물 보기</h2>${b.model?`<div class="public-model-preview">${sketch('bim','가상 공개용 모델 · 외형과 층별 형태')}</div><p>건물의 외형과 층별 형태를 회전하며 살펴볼 수 있습니다.</p>${btn('공개 3D/BIM 열기',"go('public_bim')",'primary')}`:`<div class="empty"><h3>공개 3D 자료가 아직 없습니다.</h3><p>노후건축물 기본정보는 계속 확인할 수 있습니다.</p></div>`}<p class="reviewnote">공개용으로 제공하는 모델만 표시하는 구성입니다. 실제 적재 BIM의 공개 범위는 운영 전에 정해야 합니다.</p></section></div><section class="panel compact"><div class="bar"><div><h3>이 건축물의 업무를 담당하시나요?</h3><p class="muted">로그인하면 같은 건축물의 담당 업무로 연결합니다.</p></div>${btn(signedIn?'이 건축물 업무 확인':'이 건축물 업무 확인 · 로그인',`enterLogin({screen:'case',id:${b.id}})`,'mini')}</div></section>`;};
pages.public_bim=()=>{const b=publicBuilding();if(!b.model)return publicBuildingHead('bim')+`<section class="panel empty"><h2>공개 3D 자료가 아직 없습니다.</h2><p>자료 등록 여부와 건축물의 안전 상태는 별개의 정보입니다.</p>${btn('노후건축물 정보로 돌아가기',"go('public_building')",'primary')}</section>`;return publicBuildingHead('bim')+`<div class="public-model-layout"><section class="panel model-panel"><div class="bar"><div><h2>공개 3D/BIM</h2><div class="muted">가상 모델 · 건물 외형과 층별 형태</div></div>${btn('처음 시점','resetPublicModel()','mini')}</div><div id="public-model" class="model-canvas"></div><div class="model-tools"><div><label for="model-rotation">건물 회전 <span id="rotation-value">${publicRotation}°</span></label><input id="model-rotation" type="range" min="0" max="360" value="${publicRotation}" oninput="publicRotation=Number(this.value);drawPublicModel()"></div><div class="actions">${btn('축소',"publicZoom=Math.max(.65,publicZoom-.15);drawPublicModel()",'mini')}${btn('확대',"publicZoom=Math.min(1.7,publicZoom+.15);drawPublicModel()",'mini')}</div></div><p class="muted">슬라이더로 회전하거나 층을 선택하세요. ‘처음 시점’으로 언제든 돌아올 수 있습니다.</p></section><section class="panel"><h2>어느 층을 볼까요?</h2><div class="floor-buttons">${[0,...Array.from({length:b.floors},(_,i)=>i+1)].map(f=>`<button id="floor-button-${f}" class="${publicFloor===f?'active':''}" onclick="publicFloor=${f};drawPublicModel()">${f===0?'전체 보기':f+'층'}</button>`).join('')}</div><div id="public-floor-info" class="notice blue"></div><h3>공개 모델 안내</h3><dl class="kv"><dt>제공 범위</dt><dd>외형 · 층 구분 · 기본 용도</dd><dt>자료 성격</dt><dd>시안용 가상 모델</dd><dt>기준일</dt><dd>2026.09.15</dd></dl><p class="muted">이 모델은 현재 안전 상태를 판정하는 자료가 아닙니다. 모델의 모습과 실제 현황에는 차이가 있을 수 있습니다.</p>${btn('노후건축물 기본정보',"go('public_building')",'text')}</section></div>`;};
function resetPublicModel(){publicRotation=32;publicFloor=0;publicZoom=1;drawPublicModel();}
function drawPublicModel(){const b=publicBuilding(),rad=publicRotation*Math.PI/180;const project=(x,y,z)=>{const u=x*Math.cos(rad)-y*Math.sin(rad),v=x*Math.sin(rad)+y*Math.cos(rad);return [360+u*1.6*publicZoom,345+(v*.60-z*1.55)*publicZoom];};const points=p=>p.map(v=>project(...v).map(n=>n.toFixed(1)).join(',')).join(' ');let parts=[];for(let f=1;f<=b.floors;f++){const z0=(f-1)*45,z1=f*45,pts=[[-95,-65,z0],[95,-65,z0],[95,65,z0],[-95,65,z0],[-95,-65,z1],[95,-65,z1],[95,65,z1],[-95,65,z1]];for(const [indices,color] of [[[0,1,5,4],'#769cba'],[[1,2,6,5],'#abc5d9'],[[2,3,7,6],'#88afca'],[[3,0,4,7],'#adc9df'],[[4,5,6,7],'#d5e4ef']]){const vs=indices.map(i=>pts[i]);const depth=vs.reduce((s,p)=>s+p[0]*Math.sin(rad)+p[1]*Math.cos(rad),0)/vs.length;parts.push({f,z:z0,depth,vs,color});}}parts.sort((a,b)=>a.z-b.z||a.depth-b.depth);$('#public-model').innerHTML=`<svg viewBox="0 0 720 470" role="img" aria-label="${b.name}의 회전 가능한 가상 공개 3D 모델"><defs><pattern id="ground-grid" width="35" height="35" patternUnits="userSpaceOnUse"><path d="M35 0H0V35" fill="none" stroke="#dee7ee"/></pattern></defs><rect width="720" height="470" fill="#f4f7fa"/><rect x="20" y="25" width="680" height="410" fill="url(#ground-grid)"/><ellipse cx="360" cy="352" rx="185" ry="64" fill="#23435c12"/>${parts.map(p=>`<polygon points="${points(p.vs)}" fill="${publicFloor===p.f?'#67a9dc':p.color}" fill-opacity="${publicFloor&&publicFloor!==p.f?.18:1}" stroke="#537b9c" stroke-opacity="${publicFloor&&publicFloor!==p.f?.25:1}" stroke-width="1.3"/>`).join('')}<text x="30" y="445" fill="#657e91" font-size="13">${b.name} · 지상 ${b.floors}층 · 가상 공개 모델</text></svg>`;$('#rotation-value').textContent=publicRotation+'°';$('#model-rotation').value=publicRotation;$('#public-floor-info').innerHTML=`<strong>${publicFloor?publicFloor+'층 선택':'전체 건물'}</strong>${publicFloor?'선택한 층을 강조했습니다.':`지상 ${b.floors}개 층의 외형을 함께 봅니다.`}<p>${b.use} · ${b.dong}</p>`;for(let f=0;f<=b.floors;f++)document.getElementById('floor-button-'+f)?.classList.toggle('active',f===publicFloor);}
// Work dashboards use current case state alongside remembered views.
buildings[0].agency='예시 B점검기관';
function workspaceRows(){return role==='official'?(dashboardScope==='mine'?buildings.slice(0,2):buildings):(dashboardScope==='mine'?[buildings[1]]:buildings.slice(0,2));}
function filteredWorkRows(){return workspaceRows().filter(b=>(listFilter==='전체'||b.type===listFilter)&&(!query||normalize(`${b.name}${b.address}${b.dong}`).includes(normalize(query)))&&(listStatus==='전체'||b.id===2&&state.phase!=='draft'));}
function setScope(scope){dashboardScope=scope;profile().scope=scope;go('home');}
function clearWorkFilters(){listFilter='전체';listStatus='전체';query='';go('home');}
function taskUpdate(){if(role==='official'){if(state.phase==='requested')return ['보완 요청 응답 대기','주민회관 · 2회차 / 요청한 F-03의 응답을 기다리고 있습니다.','요청 현황 보기','requested'];if(state.phase==='resubmitted')return ['보완본 v2 도착','주민회관 · 2회차 / 원문과 바뀐 설명을 확인하세요.','변경 항목 검토','review'];if(state.phase==='complete')return ['결과 검토 완료','주민회관 · 2회차 / 후속 일정과 원천 처리 여부를 확인하세요.','처리 이력 보기','history'];if(state.phase==='draft')return ['기관 자료 준비 중','주민회관 · 2회차 / 아직 공유된 검토본이 없습니다.','진행 현황 보기','case'];return ['새 공유 결과 1건','주민회관 · 2회차 / 보고서 v1과 연결된 근거를 확인하세요.','공유 결과 검토','review'];}if(state.phase==='requested')return ['새 보완 요청 1건','주민회관 · 2회차 / 옥상 난간의 위치 설명 보완 요청','요청 항목에 응답','reply'];if(state.phase==='complete')return ['공무원 검토 완료','주민회관 · 2회차 / 공유한 결과의 검토 이력이 갱신됐습니다.','결과 확인','complete'];if(['shared','resubmitted'].includes(state.phase))return ['공유본 검토 현황','주민회관 · 2회차 / 공무원의 확인 상태를 볼 수 있습니다.','공유 현황 보기','shared'];return ['사업 일정 확인','주민회관 · 2회차 / 사업 일정 2026.09.30을 확인하세요.','해당 점검건 열기','case'];}
pages.home=()=>{const p=profile(),r=p.recent,b=buildings.find(x=>x.id===r.selected)||buildings[1],update=taskUpdate(),rows=filteredWorkRows();return `<div class="bar dashboard-title"><div><div class="eyebrow">${role==='official'?'지자체 노후건축물 안전진단 관리':'전문기관 점검 업무'}</div><h1>내 업무 대시보드</h1><p class="muted">${restoredLogin?`이전 조회환경 복원 · ${esc(restoreTime)}`:'담당 업무와 최근 작업에서 시작합니다.'} · 업무 상태는 현재 예시 기준</p></div><div class="scope-switch">${btn('내 담당',"setScope('mine')",dashboardScope==='mine'?'active':'')}${btn(role==='official'?'관할 전체':'기관 전체',"setScope('all')",dashboardScope==='all'?'active':'')}</div></div><div class="dashboard-focus"><section class="panel resume-panel"><div class="eyebrow">이어서 할 업무</div><h2>${b.name} · ${b.dong}</h2><p>${b.type} · ${b.round}</p><p class="muted">최근 화면: ${explanations[r.screen]?.[0]||'업무 상세'} · ${p.visited?'이 브라우저에서 이어가기':'이전 작업 예시'}</p><div class="actions">${btn('최근 작업 이어가기','continueWork()','primary')}${btn('이전 조회조건 보기',"go('list')",'text')}</div></section><section class="panel update-panel"><div class="eyebrow">현재 확인할 변화·요청</div><h2>${update[0]}</h2><p>${update[1]}</p><p class="muted">최근 작업의 조회조건과 관계없이 표시합니다.</p>${btn(update[2],`go('${update[3]}',{id:2})`)}</section></div><section class="panel"><div class="bar"><div><h2>${dashboardScope==='mine'?'내 담당 업무':role==='official'?'관할 전체 업무':'기관 전체 업무'}</h2><div class="muted">${chip(listFilter)} ${chip(listStatus)} ${query?chip('검색: '+esc(query)):''} · ${rows.length}건 · 현재 상태 기준</div></div><div class="actions">${btn('조회조건 변경',"go('list')",'mini')}${btn('조건 초기화','clearWorkFilters()','text mini')}</div></div>${caseTable(rows)}<p class="muted">${role==='official'?'내 담당은 예시 담당 건, 관할 전체는 소속 지자체의 업무를 보여줍니다.':'내 담당은 개인 배정 건, 기관 전체는 같은 기관의 다른 담당자 업무를 함께 보여줍니다.'}</p></section>`;};
const originalListPage=pages.list;
pages.list=()=>originalListPage().replace('조회범위: 내 관할',`조회범위: ${dashboardScope==='mine'?'내 담당':'관할 전체'}`).replace('조회범위: 내 기관 담당·공유 건',`조회범위: ${dashboardScope==='mine'?'내 담당':'기관 전체'}`);
function analysisRows(){let ids=role==='official'?[2,3]:[2];if(analysisFilter==='점검기록 있음')ids=ids.filter(x=>x===2);if(analysisFilter==='연결 확인 필요')ids=ids.filter(x=>x===3);return publicBuildings.filter(x=>ids.includes(x.id));}
pages.region=()=>{const rows=analysisRows();return `<div class="bar"><div><div class="eyebrow">업무용 지도 분석</div><h1>${role==='official'?'관할 현황·대상 선별':'담당 노후건축물·현장 분석'}</h1><p class="muted">${role==='official'?'관할: 예시시':'범위: 내 기관의 담당 건'} · 분석 조건과 선택 후보를 유지합니다.</p></div>${btn('작업 화면으로 돌아가기',"openWorkspace('work')")}</div><section class="panel compact"><div class="filters"><div><label for="analysis-filter">후보의 자료 상태</label><select id="analysis-filter">${['전체','점검기록 있음','연결 확인 필요'].map(v=>`<option ${v===analysisFilter?'selected':''}>${v}</option>`).join('')}</select></div>${btn('분석 조건 적용',"analysisFilter=document.querySelector('#analysis-filter').value;go('region')",'primary')}<span class="muted">${rows.length}건 · 자료 기준일 2026.09.15 · 가상 조건</span></div></section><div class="public-map-layout"><section class="panel map-surface">${cityMap(rows,false)}<div class="map-caption">검토 후보의 위치입니다. 법정 안전등급 판정은 아닙니다.</div></section><section class="panel"><h2>같은 조건의 후보 · ${rows.length}건</h2>${rows.length?rows.map(b=>`<section class="candidate-result"><h3>${b.name} · ${b.dong}</h3><p>${b.id===2?'이전 관찰기록과 이번 회차 자료 대조':'동 식별정보와 대장 연결 확인 필요'}</p><p class="muted">${b.id===2?stageName():'원천 자료 확인 필요'}</p>${btn('근거·기존 점검 확인',b.id===2?"go('candidate')":"openCase(3)",'mini')}</section>`).join(''):'<div class="empty">현재 조건에 해당하는 담당 후보가 없습니다.</div>'}<p class="muted">공개 지도와 같은 건축물 식별을 사용하고, 권한에 맞는 업무·검토 정보를 연결하는 구성입니다.</p></section></div>`;};
const originalCandidate=pages.candidate;
pages.candidate=()=>originalCandidate().replace("go('region')","openWorkspace('analysis')");
Object.assign(explanations,{
 landing:['업무가 우선인 공통 메인','직전 시안은 공개 조회를 왼쪽에 크게 배치하고 일반 건축물 정보 서비스처럼 소개했습니다.','매일 이용하는 담당자의 업무 입구가 뒤로 밀리고, 노후건축물 안전진단 관리라는 주목적을 알아보기 어려웠습니다.','왼쪽에 지자체·전문기관 업무를 먼저 배치하고 오른쪽에 비로그인 GIS+sBIM 정보조회를 보조 경로로 제공합니다.','모바일과 키보드 순서도 업무가 먼저입니다. 서비스 대상은 관리가 필요하거나 검토가 필요한 노후건축물이며, 노후라는 이유로 위험을 단정하지 않습니다.'],
 public_map:['비로그인 공개 검색·지도','기존 탐색은 관리자 계정으로 진행해 실제 비로그인 공개 범위는 확인하지 못했습니다.','특정 건물을 찾는 사람에게 복잡한 업무 필터와 로그인 절차를 함께 보여주면 탐색이 길어집니다.','주소·건물명 검색, 지도와 같은 조건의 목록, 공개 3D 유무를 간단히 제공합니다.','새로 제안한 공개 조회 경로입니다. 실제 공개할 데이터·모델은 운영 전에 확정해야 합니다.'],
 public_building:['공개 건축물 요약','업무용 상세에는 업무 상태·회차·기관·기술 자료가 함께 있습니다.','일반 이용자는 어떤 정보가 공개 자료인지, 자료가 없으면 무엇을 뜻하는지 알기 어렵습니다.','기본정보, 공개 자료의 출처·기준일, 공개 3D 유무를 이해하기 쉽게 보여줍니다.','공개 자료 없음과 실제 점검 미실시·안전 판정을 구분할 수 있습니다.'],
 public_bim:['공개용 3D/BIM 열람','적재 BIM에는 외형 외에 실내·구조 속성·결함 정보가 포함될 수 있습니다.','모든 모델 정보를 한꺼번에 공개하거나 전문 조작 도구를 그대로 보이면 공개 범위와 사용 목적이 어긋납니다.','공개용 모델의 외형·층 구분부터 회전·확대·층 선택으로 열람합니다.','현재 시안은 별도의 가상 모델입니다. 실제 BIM의 공개 권한·속성 범위를 확정했다는 뜻은 아닙니다.'],
 home:['최근 작업을 복원한 업무 대시보드','이전 시안은 로그인할 때마다 같은 초기 상태로 돌아갔습니다.','어제 보던 건과 조건을 다시 찾아야 하고, 마지막 화면만 복원하면 새 요청을 놓칠 수 있습니다.','최근 건·회차·조회조건을 유지하고 현재 요청·상태와 내 담당/전체 범위를 함께 보여줍니다.','작업 복귀와 현재 상황 파악을 함께 지원합니다. 가상 작업은 이 브라우저에만 보관합니다.'],
 region:['별도 지도 분석 탭','이전 구조에서는 지도와 업무 화면이 서로 다른 진입 체계에 있었습니다.','지도 분석 후 작성 중인 건으로 돌아갈 때 작업 위치와 조회조건을 잃기 쉽습니다.','상단 내 업무/지도 분석을 나누고 두 공간의 최근 화면·조건을 각각 유지합니다.','분석과 업무를 오가며 필요한 건만 명시적으로 연결할 수 있습니다.']
});
explanations.login=['업무 로그인과 목적지 유지','이전 시안은 모든 로그인에서 같은 기본 업무 홈으로 이동했습니다.','특정 건축물에서 업무를 확인하려고 로그인했어도 다시 그 건을 찾아야 했습니다.','일반 로그인은 복원된 대시보드로, 특정 건에서 요청한 로그인은 권한을 확인한 같은 건으로 연결합니다.','기본 시작점과 사용자가 이미 선택한 목적지를 함께 존중합니다.'];
let stagePreview=false;
const persistNormal=persistDemo;
persistDemo=function(){if(!stagePreview)persistNormal();};
const originalReset=resetDemo;
resetDemo=function(r='agency'){stagePreview=false;originalReset(r);};
const legacyJump=jumpTo;
jumpTo=function(i){stagePreview=true;signedIn=true;lastWorkView=null;lastAnalysisView=null;pendingDestination=null;legacyJump(i);if(['login','first'].includes(screen))signedIn=false;render();};
const tourSteps=[
 {label:'공통 메인 · 업무 우선·공개 조회 보조',route:'landing'},
 {label:'비로그인 검색·공개 지도',route:'public_map'},
 {label:'공개 노후건축물 정보',route:'public_building'},
 {label:'공개 3D/BIM · 회전·층 선택',route:'public_bim'},
 {label:'3D 자료가 없는 노후건축물',route:'public_building',id:3},
 {label:'선택한 노후건축물로 이어지는 로그인',route:'login',destination:2},
 {label:'최초 소속·권한 안내',legacy:1},
 {label:'공무원 대시보드 · 최근 작업과 새 결과',legacy:12,restored:true},
 {label:'업무용 지도 분석 탭',legacy:21},
 {label:'전문기관 업무 로그인',legacy:0},
 {label:'기관 대시보드 · 최근 작업',legacy:2},
 {label:'담당 점검 목록',legacy:3},
 {label:'노후건축물·동·업무유형·회차',legacy:4},
 {label:'현장 준비',legacy:5},
 {label:'현장조사·결함',legacy:6},
 {label:'근거·위치·항목 확인',legacy:7},
 {label:'보고서 준비·남은 항목',legacy:8},
 {label:'보고서 미리보기',legacy:9},
 {label:'v1 공유 전 확인',legacy:10},
 {label:'v1 결과 공유',legacy:11},
 {label:'공무원 v1 검토',legacy:13},
 {label:'항목별 보완 요청',legacy:14},
 {label:'기관 응답 대기',legacy:15},
 {label:'기관 보완 응답',legacy:16},
 {label:'v2 보완 결과 공유',legacy:17},
 {label:'공무원 v2 재검토',legacy:18},
 {label:'결과 검토 완료',legacy:19},
 {label:'원본·수정본·처리 이력',legacy:20},
 {label:'지도 후보와 기존 점검 연결',legacy:22},
 {label:'자료 연결 확인·복구 경로',legacy:23},
 {label:'재로그인 · 이전 조회조건 복원',legacy:2,restored:true},
 {label:'보고서 선택 목록',legacy:2,after:'reports'},
 {label:'노후건축물·회차 이력 목록',legacy:12,after:'histories'}
];
function showTourStep(i){const t=tourSteps[i];if(!t)return;$('#dialog').close();stagePreview=true;publicSelected=t.id||2;publicQuery='';publicFilter='전체';publicRotation=32;publicFloor=0;publicZoom=1;dashboardScope='mine';formDrafts={};restoredLogin=!!t.restored;restoreTime='09.14. 17:30';demoProfiles={};pendingDestination=null;if(t.legacy!==undefined){jumpTo(t.legacy);const p=profile();p.visited=!!t.restored;p.updated='09.14. 17:30';p.recent={...workContext(),screen:role==='official'?'review':'prep'};if(t.restored){listFilter='소규모 노후건축물 점검';query='주민';p.filters={listFilter,listStatus:'전체',query};}if(t.after)go(t.after);else render();}else{signedIn=false;role='official';if(t.destination)pendingDestination={screen:'case',id:t.destination};go(t.route);}clearTimeout(window.toastTimer);$('#toast').style.display='none';}
showJourney=function(){modal('노후건축물 안전진단 업무 · 전체 시안',`<p>공통 메인에서 목적에 맞는 경로를 선택합니다. 업무 중에는 하단의 역할 전환으로 담당자 인계를 체험할 수 있습니다.</p><p>${btn('공통 메인으로',"document.querySelector('#dialog').close();returnToStart()",'primary')}</p><p class="muted">아래 단계 선택은 독립적인 가상 예시입니다. 단계 미리보기는 브라우저의 보관 기록을 갱신하지 않습니다.</p><div class="journeybuttons">${tourSteps.map((t,i)=>btn(`${String(i+1).padStart(2,'0')}. ${t.label}`,`showTourStep(${i})`)).join('')}</div>`);};
renderViewer=function(){let handoff='';if(signedIn&&!publicRoutes.has(screen)){if(state.phase==='shared'&&role==='agency')handoff=btn('공무원 검토로 이어보기',"switchActor('official','review')",'primary');if(state.phase==='requested'&&role==='official')handoff=btn('기관 보완 응답으로 이어보기',"switchActor('agency','reply')",'primary');if(state.phase==='resubmitted'&&role==='agency')handoff=btn('공무원 재검토로 이어보기',"switchActor('official','review')",'primary');}$('#viewer').innerHTML=`<div><strong>시안 검토 도구</strong> · ${publicRoutes.has(screen)?'공개 조회·진입':role==='official'?'공무원':'전문기관'} · ${explanations[screen]?.[0]||'업무 화면'}<br><span>${stagePreview?'단계 미리보기 · 보관 기록 갱신 없음':storageOK?'가상 작업은 이 브라우저에 보관 · 실제 서버 전송 없음':'브라우저 보관 불가 · 현재 창의 가상 상태만 유지'}</span></div><div class="actions">${handoff}${btn('전체 화면 순서','showJourney()')}${btn('시안 기록 초기화',"showResetHelp()")}</div>`;};
function showResetHelp(){modal('가상 시안 기록 초기화',`<p>이 브라우저에 보관한 가상 작업·조회조건을 지우고 공통 메인으로 돌아갑니다. 실제 플랫폼 데이터와는 관계없습니다.</p><div class="actions">${btn('가상 기록 초기화',"document.querySelector('#dialog').close();resetDemo('agency')",'primary')}${btn('돌아가기',"document.querySelector('#dialog').close()")}</div>`);}
pages.access_unavailable=()=>`<section class="panel"><div class="eyebrow">업무 열람 범위 확인</div><h1>현재 계정의 담당 범위에 포함되지 않습니다.</h1><p>${publicBuildings.find(b=>b.id===deniedCaseId)?.name||'선택한 건축물'}의 공개 정보는 계속 볼 수 있습니다.</p><p class="muted">업무 자료는 소속과 배정 범위를 확인한 후 열람하는 구성입니다.</p><div class="actions">${btn('공개 정보 계속 보기',`publicSelected=${deniedCaseId};go('public_building')`,'primary')}${btn('내 업무로 돌아가기',"go('home',{id:2})")}</div></section>`;
explanations.access_unavailable=['업무 범위 확인','공개 조회와 기관 업무 조회는 허용 범위가 다릅니다.','로그인만 하면 모든 건축물의 업무를 볼 수 있는 것처럼 연결되면 역할 구분이 무의미해집니다.','계정의 담당 범위를 확인하고 허용되지 않는 건은 공개 정보와 내 업무로 연결합니다.','공개 조회 경로를 유지하면서 업무 권한의 경계를 명확히 합니다.'];
const dataForOfficial=pages.data;
pages.data=()=>role==='official'?dataForOfficial():`<div class="bar"><div><h1>담당 노후건축물의 자료 연결</h1><p class="muted">조회범위: 예시 B점검기관 · 담당 자료</p></div></div><section class="panel"><h2>예시 주민회관 · 본동 / 2026년 2회차</h2><dl class="kv"><dt>대장·동 정보</dt><dd>연결 확인됨</dd><dt>현장 근거</dt><dd>${state.evidence?'자료 확인됨':'위치 설명 확인 필요'}</dd><dt>BIM</dt><dd>연결됨 · 보조 열람</dd><dt>BLCM 처리</dt><dd>별도 확인</dd></dl><div class="actions">${btn('담당 점검건 열기',"openCase(2)",'primary')}${btn('모델을 열 수 없는 경우','showBimFallback()')}</div></section>`;
pages.reports=()=>`<div class="bar"><div><h1>점검결과·보고서</h1><p class="muted">조회범위: ${dashboardScope==='mine'?'내 담당':role==='official'?'관할 전체':'기관 전체'} · 건축물·회차를 선택하세요.</p></div></div><section class="panel"><table><thead><tr><th>건축물·동 / 회차</th><th>보고서·자료 상태</th><th>보기</th></tr></thead><tbody>${workspaceRows().map(b=>`<tr><td>${b.name} · ${b.dong}<small>${b.type} · ${b.round}</small></td><td>${b.id===2?stageName():caseStatus(b)}</td><td>${btn(b.id===2?'보고서 열기':'업무 자료 확인',b.id===2?"go('report',{id:2})":`openCase(${b.id})`,'mini')}</td></tr>`).join('')}</tbody></table></section>`;
pages.histories=()=>`<div class="bar"><div><h1>노후건축물·점검 이력</h1><p class="muted">조회범위: ${dashboardScope==='mine'?'내 담당':role==='official'?'관할 전체':'기관 전체'}</p></div></div><section class="panel"><table><thead><tr><th>건축물·동</th><th>업무유형·회차</th><th>보기</th></tr></thead><tbody>${workspaceRows().map(b=>`<tr><td>${b.name} · ${b.dong}</td><td>${b.type}<small>${b.id===2?'2025년 1회차 / 2026년 2회차':b.round+' · 원천 기록 확인'}</small></td><td>${btn(b.id===2?'회차·버전 이력 열기':'업무 개요',b.id===2?"go('history',{id:2})":`openCase(${b.id})`,'mini')}</td></tr>`).join('')}</tbody></table></section>`;

// Auto-capture local draft text without marking a report as complete.
document.addEventListener('input',e=>{if(['opinion','evidence-caption','request-text','reply-text'].includes(e.target.id)){rememberDraft();persistDemo();}});
window.addEventListener('pagehide',()=>{rememberDraft();rememberWork();persistDemo();});
screen='landing';render();history.replaceState(navContext(),'','#landing');

function returnToStart(){if(stagePreview){location.href=new URL('workflow.html',location.href).href;}else go('landing');}
