const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(label,fn,cls='')=>`<button class="${cls}" onclick="${fn}">${label}</button>`;
const chip=(label,cls='')=>`<span class="chip ${cls}">${label}</span>`;
const demoOpinion='[가상 예시] 이번 회차의 현장 관찰자료와 이전 기록을 대조했습니다. 위치별 사진과 관찰 내용을 해당 점검 항목에 연결했으며, 추가 확인이 필요한 사항은 별도 검토 항목으로 정리했습니다.';
const buildings=[{id:1,name:'예시 중앙상가',dong:'가동',address:'예시시 중앙로 10',type:'정기점검',round:'3회차',due:'2026.09.25',agency:'예시 A점검기관'},{id:2,name:'예시 주민회관',dong:'본동',address:'예시시 안전로 20',type:'소규모 노후건축물 점검',round:'2026년 2회차',due:'사업 일정 2026.09.30',agency:'예시 B점검기관'},{id:3,name:'예시 문화시설',dong:'나동',address:'예시시 문화로 30',type:'3종건축물 지정 실태조사',round:'2026년 1회차',due:'조사 일정 확인 필요',agency:'예시 C조사기관'}];
const defects=[{id:'F-01',place:'1층 계단실',part:'벽',item:'구조안전 → 마감 → 내부 칸막이벽',kind:'균열',value:'최대폭 2.0mm · 길이 1.5m',before:'최대폭 2.2mm · 길이 1.5m',status:'관찰 기록 있음'},{id:'F-02',place:'2층 복도 천장',part:'슬래브',item:'구조안전 → 구조물 → 주요부재',kind:'균열',value:'최대폭 0.3mm · 길이 1.5m',before:'최대폭 0.4mm · 길이 1.5m',status:'관찰 기록 있음'},{id:'F-03',place:'옥상 출입구 주변',part:'난간',item:'구조안전 → 마감 → 옥상 난간',kind:'위치·사진 확인',value:'현장 관찰 및 사진 설명',before:'이전 사진 기록 있음',status:'근거 설명 확인 필요'}];
let role='official',screen='login',selected=2,selectedDefect='F-03',listFilter='전체',query='',listStatus='전체',fieldMode='항목 기준',candidateChoice=false;
function initialState(r){const official=r==='official';return {phase:official?'shared':'draft',field:official,evidence:official,opinion:official?demoOpinion:'',version:1,reviewChecked:false,request:'',reply:'',snapshots:official?[{version:1,opinion:demoOpinion,note:'최초 공유본',captions:{'F-03':'[가상 예시] 옥상 난간 촬영 위치 기록입니다.'}}]:[],events:official?['v1 보고서 결과 공유 · 예시 B점검기관']:['2026년 2회차 현장 점검 자료 준비'],candidate:false,captions:{}};}
let state=initialState(role);
function canEdit(){return role==='agency'&&state.phase==='draft';}
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',3200);}
function modal(title,content){$('#dialog').innerHTML=`${btn('닫기',"document.querySelector('#dialog').close()",'dialogclose mini')}<h2>${title}</h2>${content}`;$('#dialog').showModal();}
function stageName(){return ({draft:'자료·보고서 준비',shared:`v${state.version} 결과 공유`,requested:'보완 요청',resubmitted:`v${state.version} 보완 결과 공유`,complete:'결과 검토 완료'})[state.phase];}
function building(){return buildings.find(b=>b.id===selected)||buildings[1];}
function caseStatus(b){return b.id===2?stageName():b.id===1?'작성 현황 확인':'대장 연결 확인 필요';}
function nextTask(b){if(b.id===1)return role==='official'?'기관의 작성 현황 확인':'원천 보고자료와 첨부 확인';if(b.id===3)return '대장 연결 자료 확인';return role==='official'?({draft:'기관 자료 준비 현황 확인',shared:`공유된 v${state.version} 보고서 검토`,requested:'기관 보완 응답 대기',resubmitted:`v${state.version} 변경·보완 항목 확인`,complete:'검토 이력·후속 확인'})[state.phase]:({draft:state.field?'보고서 의견 정리':'이번 회차 현장 근거 확인',shared:'공유 버전·검토 현황 확인',requested:'요청 항목의 보완 결과 작성',resubmitted:'재검토 현황 확인',complete:'검토 결과·후속 확인'})[state.phase];}
function navContext(){return {screen,selected,selectedDefect,listFilter,query,listStatus,fieldMode,role};}
function go(s,opts={}){if(opts.id)selected=opts.id;screen=s;render();if(!opts.pop)history.pushState(navContext(),'',`#${s}`);window.scrollTo(0,0);}
window.addEventListener('popstate',e=>restoreNavigation(e.state));
function pickRole(r){role=r;go('login');}
function login(){state=initialState(role);selected=2;listFilter='전체';query='';listStatus='전체';go('home');toast('가상 계정으로 업무 메인화면에 진입했습니다.');}
function switchActor(r,s){role=r;go(s);toast(`${r==='official'?'공무원':'전문기관'} 시안으로 전환했습니다. 같은 점검건·공유 버전을 유지합니다.`);}
function listGo(type='전체',status='전체'){listFilter=type;listStatus=status;query='';go('list');}
function openCase(id){selected=id;go('case');}
function caseHead(tab='case'){
const b=building();return `<div class="breadcrumb">${btn('점검 목록',"go('list')",'text')} / ${b.type} / ${b.round}</div><section class="casehead"><div class="bar"><div><div class="eyebrow">${b.type} · ${b.round}</div><h1>${b.name} · ${b.dong}</h1><div class="muted">${b.address} · 현장: 예시시 공공시설 점검사업</div></div><div>${chip(b.id===2?stageName():caseStatus(b),'blue')}</div></div><div class="keyrow"><span>담당기관 <strong>${b.agency}</strong></span><span>일정 ${b.due}</span><span>자료 기준일 2026.09.15</span></div>${b.id===2?`<div class="statusgrid"><div><small>현장자료 확인</small>${state.field?'확인 완료':'확인 중'}</div><div><small>보고서</small>${state.opinion?'의견 정리됨':'의견 작성 필요'}</div><div><small>플랫폼 내 결과 검토</small>${stageName()}</div><div><small>BLCM 법정 처리</small>별도 확인</div></div>`:''}<div class="tabs">${[['case','업무 요약'],['prep','현장 준비'],['field','현장조사·결함'],['report','보고서'],['history','이전 회차·이력']].map(([k,v])=>btn(v,`go('${k}')`,tab===k?'active':'')).join('')}</div></section>`;
}
function steps(current){return `<div class="muted">업무 화면 순서 · 파란색은 현재 열람 위치</div><div class="stepstrip">${['현장 준비','현장자료 확인','보고서 준비','결과 공유','검토·보완','검토 완료'].map((v,i)=>`<span class="${i===current?'on':''}">${i+1}. ${v}</span>`).join('')}</div>`;}
function render(){
$('#header').innerHTML=`<div class="brand">안전워치<small>노후건축물 안전진단 업무 지원</small></div><div class="account">${screen==='login'?'업무 계정으로 시작합니다':`<strong>${role==='official'?'예시시 · 건축안전 담당':'예시 B점검기관 · 점검 담당'}</strong>${role==='official'?'관할: 예시시 전체 · 공무원':'범위: 내 기관 담당·공유 건 · 전문기관'}`}</div>`;
const auth=screen==='login'||screen==='first';$('#sidebar').style.display=auth?'none':'';$('#shell').style.gridTemplateColumns=auth?'1fr':'';
$('#sidebar').innerHTML=`<h3>${role==='official'?'공무원 업무':'전문기관 업무'}</h3>${[['home','내 업무'],['list','노후건축물·점검 현황'],['reports','점검결과·보고서'],['histories','노후건축물·점검 이력']].map(([k,v])=>btn(v,`go('${k}')`,screen===k?'active':'')).join('')}${role==='official'?btn('관할 현황·대상 선별',"go('region')",['region','candidate'].includes(screen)?'active':''):''}<h3>자료 확인</h3>${btn('연결 확인이 필요한 자료',"go('data')",screen==='data'?'active':'')}<div class="scope">2026년 업무 자료<br>건축물 · 동 · 업무유형 · 회차를 기준으로 연결합니다.</div>`;
const scoped=['prep','field','defect','report','preview','share','shared','review','supplement_request','requested','reply','resubmitted','complete','history'];
let renderer=pages[screen]||pages.home;
if(selected!==2&&scoped.includes(screen))renderer=()=>caseHead('case')+otherCase(building());
else if(screen==='complete'&&state.phase!=='complete')renderer=pages.case;
else if(screen==='share'&&!canEdit())renderer=pages.shared;
else if(screen==='reply'&&(role!=='agency'||state.phase!=='requested'))renderer=pages.case;
else if(['review','supplement_request'].includes(screen)&&role!=='official')renderer=pages.shared;
$('#app').innerHTML=renderer();
if(!canEdit()){
 if(screen==='defect'){$('#evidence-caption')?.setAttribute('readonly','');$('#evidence-check')?.setAttribute('disabled','');if($('#confirm-evidence'))$('#confirm-evidence').outerHTML='<p class="notice blue">공유 근거 열람 중 · 원문을 보존합니다.</p>';}
 if(screen==='field'){const b=$('[onclick="finishField()"]');if(b){b.disabled=false;b.textContent='연결된 보고서 보기';b.setAttribute('onclick',"go('preview')");}}
 if(screen==='report'){
  $('#opinion')?.setAttribute('readonly','');
  for(const sel of ['[onclick="saveOpinion()"]','[onclick="showOpinionExample()"]'])if($(sel))$(sel).style.display='none';
  const b=document.querySelector('[onclick="go(\'share\')"]');if(b){b.disabled=false;b.textContent=role==='official'?'공유본 검토':state.phase==='requested'?'보완 요청에 응답':'공유·검토 현황';b.setAttribute('onclick',`go('${role==='official'?'review':state.phase==='requested'?'reply':'shared'}')`);}
 }
}
renderViewer();}
const pages={};
pages.login=()=>`<div class="loginwrap"><div class="loginintro"><div class="eyebrow">LOGIN → MY WORK</div><h1>담당 노후건축물의 점검을<br>한 흐름에서 이어갑니다.</h1><p>지자체의 관할 안전관리와 전문기관의 현장점검·보고서 업무를 지원합니다.</p><ul><li>점검유형과 회차별로 현재 업무 확인</li><li>현장사진·이전 기록·BIM 근거 연결</li><li>공유한 보고서와 보완 이력 확인</li></ul><div class="loginsteps"><span>로그인</span><span>역할별 메인화면</span><span>담당 점검</span><span>결과·이력</span></div></div><section class="logincard"><h2>업무 계정 로그인</h2><p class="muted">아래 역할 선택은 시안 검토용입니다.</p><div class="loginrole">${btn('지자체 담당자',"pickRole('official')",role==='official'?'active':'')}${btn('전문기관 담당자',"pickRole('agency')",role==='agency'?'active':'')}</div><label for="demo-id">아이디</label><input class="full" id="demo-id" value="${role==='official'?'예시 공무원 계정':'예시 전문기관 계정'}" disabled><label for="demo-pw">비밀번호</label><input class="full" id="demo-pw" type="password" value="demo-only" disabled>${btn('로그인 후 메인화면 보기','login()','primary')}<div class="actions">${btn('계정 이용 안내',"showAccountHelp()",'text')}${btn('처음 이용하는 경우',"go('first')",'text')}</div><p class="reviewnote">실제 ID·비밀번호를 입력할 필요가 없습니다. 인증과 저장은 실행되지 않습니다.</p></section></div>`;
pages.first=()=>`<div style="max-width:780px;margin:25px auto"><div class="eyebrow">FIRST VISIT</div><h1>소속과 이용 가능한 업무 확인</h1><p class="muted">최초 이용자에게만 필요한 절차의 예시입니다.</p><section class="panel"><dl class="kv"><dt>소속</dt><dd>${role==='official'?'예시시 건축안전 부서':'예시 B점검기관'}</dd><dt>이용 역할</dt><dd>${role==='official'?'지자체 담당자':'점검 담당자'}</dd><dt>현재 확인 상태</dt><dd>${chip('소속·권한 확인 완료','good')}</dd><dt>이용 가능 업무</dt><dd>${role==='official'?'관할 점검 조회 · 결과 검토 · 대상 선별':'담당 점검 · 현장자료 · 보고서 준비'}</dd></dl><div class="notice blue">소속 확인 중인 사용자는 처리 상태와 문의 경로를 볼 수 있도록 설계합니다. 이미 확인된 사용자는 매번 이 단계를 거치지 않습니다.</div>${btn('확인된 계정으로 메인화면 보기','login()','primary')} ${btn('로그인 화면',"go('login')")}</section></div>`;
function showAccountHelp(){modal('업무 계정 이용 안내','<p>실제 운영에서는 기관 계정 형식, 계정 찾기, 소속·권한 확인, 접속 지원 경로를 이곳에서 안내합니다.</p><p>현재 시안에서는 어떤 계정도 조회·생성하지 않습니다. BLCM 통합로그인 가능 여부는 별도 확인이 필요합니다.</p>');}
pages.home=()=>{
const official=role==='official',b=buildings[1];return `<div class="bar"><div><div class="eyebrow">${official?'관할 노후건축물 안전관리':'내 기관의 점검 업무'}</div><h1>${official?'오늘 확인할 점검·조사':'진행 중인 점검 이어보기'}</h1><div class="muted">${official?'관할의 업무유형별 기한과 처리할 건을 확인합니다.':'현장자료와 보고서 준비 상태를 확인하고 작업을 이어갑니다.'}</div></div><div>${chip('예시 자료 · 2026.09.15')}</div></div><div class="cards">${official?`<button class="card" onclick="listGo('정기점검')"><small>정기점검</small><strong>기한·기관 현황 확인</strong><b>1건</b></button><button class="card" onclick="openCase(2)"><small>소규모 노후건축물 점검</small><strong>${state.phase==='complete'?'검토 완료한 결과':'공유 결과·보완 확인'}</strong><b>1건</b></button><button class="card" onclick="go('data')"><small>3종건축물 지정 실태조사</small><strong>대장 연결 자료 확인</strong><b>1건</b></button>`:`<button class="card" onclick="go('field',{id:2})"><small>소규모 노후건축물 점검</small><strong>이번 회차 현장자료</strong><b>${state.field?'확인 완료':'확인 중'}</b></button><button class="card" onclick="go('report',{id:2})"><small>점검보고서 준비</small><strong>의견·첨부 정리</strong><b>${state.opinion?'정리됨':'1건'}</b></button><button class="card" onclick="go('${state.phase==='requested'?'reply':'case'}',{id:2})"><small>결과 공유·검토</small><strong>${state.phase==='requested'?'보완 요청 항목':'현재 처리 상태'}</strong><b>${state.phase==='requested'?'1건':state.phase==='complete'?'확인 완료':'1건'}</b></button>`}</div><section class="panel"><div class="bar"><h2>${official?'확인할 업무':'최근 작업 · 같은 회차로 이어가기'}</h2>${btn('전체 점검 목록',"listGo()")}</div>${caseTable(official?buildings:buildings.slice(0,2))}</section><div class="grid equal"><section class="panel"><h3>${official?'관할 현황에서 후보 검토':'지난 회차 결함 비교'}</h3><p>${official?'지역별 분포를 보고 선별 근거와 점검이력으로 이어갑니다.':'이전 기록과 이번 자료를 같은 위치에서 대조합니다.'}</p>${btn(official?'지도·후보 목록 열기':'이전 회차 비교',`go('${official?'region':'history'}',{id:2})`)}</section><section class="panel"><h3>자료·연계 상태</h3><p>법정 처리 정보: ${chip('별도 확인')}</p><p class="muted">플랫폼 내부 공유·검토와 원천 시스템의 처리를 구분해서 확인합니다.</p>${btn('자료 출처와 확인 상태',"go('data')",'text')}</section></div>`;
};
function caseTable(rows){return `<div class="tablebox"><table><thead><tr><th>건축물·동 / 주소</th><th>업무유형·회차</th><th>기한·일정</th><th>진행상태</th><th>다음 확인</th></tr></thead><tbody>${rows.length?rows.map(b=>`<tr><td class="identity">${btn(`${b.name} · ${b.dong}`,`openCase(${b.id})`,'text')}<small>${b.address}</small></td><td>${b.type}<small>${b.round}</small></td><td>${b.due}</td><td>${chip(caseStatus(b),b.id===2?'blue':'warn')}</td><td>${nextTask(b)}<p>${btn('업무 건 열기',`openCase(${b.id})`,'mini')}</p></td></tr>`).join(''):'<tr><td colspan="5" class="empty">현재 조건에 해당하는 예시 업무가 없습니다. 조회조건을 초기화해 보세요.</td></tr>'}</tbody></table></div>`;}
pages.list=()=>{const base=workspaceRows(),rows=base.filter(b=>(listFilter==='전체'||b.type===listFilter)&&(!query||`${b.name} ${b.address} ${b.dong}`.includes(query))&&(listStatus==='전체'||(b.id===2&&state.phase!=='draft')));return `<div class="bar"><div><h1>노후건축물·점검 현황</h1><div class="muted">조회범위: ${role==='official'?'내 관할':'내 기관 담당·공유 건'} · 목록 단위: 업무 건</div></div>${btn('내 업무',"go('home')")}</div><section class="panel"><div class="filters"><div class="field"><label for="type-filter">업무유형</label><select id="type-filter">${['전체',...new Set(base.map(b=>b.type))].map(t=>`<option ${t===listFilter?'selected':''}>${t}</option>`).join('')}</select></div><div><label for="status-filter">진행구분</label><select id="status-filter"><option>전체</option><option ${listStatus!=='전체'?'selected':''}>공유·검토 대상</option></select></div><div><label for="search-filter">노후건축물명·주소</label><input id="search-filter" value="${esc(query)}" placeholder="노후건축물명 또는 주소"></div>${btn('조회','applyFilters()','primary')}${btn('초기화','listGo()')}</div><div class="bar"><div class="muted">${chip(listFilter)} ${chip(listStatus)} · ${rows.length}건 · 자료 기준일 2026.09.15</div><div class="muted">핵심 업무 열 우선 · 상세에서 부가 정보 확인</div></div>${caseTable(rows)}</section>`;};
function applyFilters(){listFilter=$('#type-filter').value;listStatus=$('#status-filter').value;query=$('#search-filter').value.trim();go('list');}
pages.case=()=>{const b=building();if(b.id!==2)return caseHead('case')+otherCase(b);const target=role==='official'?(state.phase==='requested'?'requested':state.phase==='complete'?'complete':'review'):(state.phase==='requested'?'reply':state.phase==='complete'?'complete':state.field?'report':'prep');return caseHead('case')+`<div class="notice blue"><strong>다음 확인: ${nextTask(b)}</strong><p>${role==='official'?'공유된 자료의 버전과 확인할 항목을 살펴보세요.':'이 건의 현장·보고서 자료를 이어서 확인하세요.'}</p>${btn('해당 업무 이어보기',`go('${target}')`,'primary')}</div>${steps(state.phase==='complete'?5:state.phase==='requested'||state.phase==='resubmitted'?4:state.phase==='shared'?3:state.field?2:0)}<div class="grid"><section class="panel"><h2>이번 점검 요약</h2><dl class="kv"><dt>현장조사일</dt><dd>2026.09.10</dd><dt>범위</dt><dd>본동 · 1~2층 및 옥상</dd><dt>현장 근거</dt><dd>예시 항목 3건 · ${state.evidence?'자료 확인됨':'위치 설명 1건 확인 필요'}</dd><dt>보고서</dt><dd>v${state.version} · ${state.opinion?'의견 정리됨':'의견 작성 필요'}</dd><dt>BIM</dt><dd>모델 연계 완료</dd></dl><div class="actions">${btn('현장 근거',"go('field')")}${btn('보고서 보기',"go('preview')")}${btn('지난 회차 비교',"go('history')")}</div></section><section class="panel"><h2>최근 이력</h2>${timeline()}<p class="muted">현재 화면의 결과 공유·보완·검토는 플랫폼 내부 협업을 가정한 흐름입니다.</p></section></div>`;};
function otherCase(b){return `<section class="panel"><h2>${b.type} 업무 요약</h2><dl class="kv"><dt>업무 상태</dt><dd>${caseStatus(b)}</dd><dt>다음 확인</dt><dd>${nextTask(b)}</dd><dt>원천 자료</dt><dd>업무 목록 자료 · 기준일 2026.09.15</dd><dt>법정 처리</dt><dd>원천 기록 별도 확인</dd></dl><div class="notice">${b.id===1?'기한과 보고 진행상태를 각각 확인합니다. 기관의 현재 작성 현황과 원천 기록을 대조하는 화면입니다.':'동 식별정보의 연결이 확인되지 않아, 자료 확인 절차로 이어집니다.'}</div><div class="actions">${btn('자료 연결 상태 확인',"go('data')")}${btn('전체 시안의 소규모 점검건 열기','openCase(2)','primary')}</div><p class="reviewnote">정기점검·3종 실태조사의 기존 서식은 유지하는 구성입니다. 상세한 완주 시나리오는 소규모 노후건축물 점검건으로 제공합니다.</p></section>`;}
function timeline(){return `<ol class="timeline">${[...state.events].reverse().map((s,i)=>`<li><small>2026.09.15 · 예시 순번 ${state.events.length-i}</small>${esc(s)}</li>`).join('')}</ol>`;}

function sketch(kind='wall',caption='가상 근거 도식 · 실제 점검 사진 아님'){
const art=kind==='roof'?`<rect x="48" y="24" width="325" height="180" fill="#fdfefe" stroke="#7890a7" stroke-width="5"/><rect x="175" y="133" width="80" height="71" fill="#dce7f0" stroke="#7890a7" stroke-width="2"/><text x="164" y="229" fill="#4d6982" font-size="15">옥상 출입구</text><path d="M373 68V155" stroke="#bd6b32" stroke-width="8"/><circle cx="345" cy="112" r="13" fill="#bd6b32"/><text x="288" y="56" fill="#4d6982" font-size="15">옥상 난간</text><text x="80" y="93" fill="#71869a" font-size="15">옥상 평면 예시</text>`:kind==='plan'?`<rect x="45" y="30" width="330" height="165" fill="#fff" stroke="#6f879f" stroke-width="4"/><path d="M175 30V195M275 30V195M45 115H375" stroke="#6f879f" stroke-width="3"/><text x="82" y="78" fill="#62788f" font-size="16">계단실</text><text x="200" y="78" fill="#62788f" font-size="16">복도</text><text x="293" y="155" fill="#62788f" font-size="16">자료실</text><circle cx="166" cy="142" r="14" fill="#bf6c32"/><text x="160" y="147" fill="white" font-size="14">1</text>`:kind==='bim'?`<path d="M90 145L220 55L345 108L215 200Z" fill="#dfe9f4" stroke="#6e8eac" stroke-width="2"/><path d="M90 145V85L220 10L345 60V108M215 200V139M90 85L215 139L345 60M155 48V113M277 35V86M155 177V112M282 155V99" fill="none" stroke="#7292b0" stroke-width="2"/><circle cx="155" cy="120" r="8" fill="#c4662f"/><text x="22" y="222" font-size="13" fill="#62778e">선택한 부재 위치와 현장 기록을 함께 확인</text>`:`<rect x="40" y="22" width="340" height="185" fill="#dce2e8"/><path d="M40 70H380M40 122H380M40 175H380M110 22V207M260 22V207" stroke="#bec9d5" stroke-width="2"/><path d="M202 40L187 71L210 95L194 121L209 144L199 180" fill="none" stroke="#6b747e" stroke-width="3"/><circle cx="202" cy="120" r="65" fill="none" stroke="#b96d35" stroke-width="2" stroke-dasharray="6 4"/><text x="282" y="59" fill="#735129" font-size="14">관찰 위치</text><path d="M278 62L243 77" stroke="#b96d35"/>`;
return `<div class="evidence"><svg viewBox="0 0 420 235" role="img" aria-label="${esc(caption)}">${art}</svg><small>${caption}</small></div>`;
}
pages.prep=()=>caseHead('prep')+steps(0)+`<div class="grid"><section class="panel"><h2>현장 방문 전에 확인할 자료</h2><div class="tablebox"><table><thead><tr><th>자료</th><th>확인 상태</th><th>열기</th></tr></thead><tbody><tr><td>건축물 개요·동 정보</td><td>${chip('이번 점검 대상과 연결됨','good')}</td><td>${btn('자료 정보',"showSource('대장')",'mini')}</td></tr><tr><td>이전 회차 점검기록</td><td>2025년 1회차</td><td>${btn('비교 보기',"go('history')",'mini')}</td></tr><tr><td>평면도·위치 정보</td><td>1층·2층·옥상</td><td>${btn('위치 보기',"showSource('평면도')",'mini')}</td></tr><tr><td>건축 BIM</td><td>${chip('연계 완료')}</td><td>${btn('3D 보기',"showSource('BIM')",'mini')}</td></tr></tbody></table></div><div class="notice blue">이전 지적 위치와 이번 점검범위를 먼저 확인합니다. 모델이 없는 건에서도 자료·사진·기록을 볼 수 있도록 구성합니다.</div><div class="pageactions">${btn('업무 요약',"go('case')")}${btn('현장자료 확인으로',"go('field')",'primary')}</div></section><section class="panel"><h2>이번 현장 범위</h2>${sketch('plan')}<dl class="kv"><dt>현장</dt><dd>예시시 공공시설 점검사업</dd><dt>대상</dt><dd>예시 주민회관 · 본동</dd><dt>이번 회차</dt><dd>2026년 2회차</dd><dt>확인할 위치</dt><dd>계단실 벽 · 복도 천장 · 옥상 난간</dd></dl></section></div>`;
function showSource(type){modal(type==='BIM'?'3D·결함 위치':`${type} 자료 확인`,type==='BIM'?sketch('bim'):`${type==='평면도'?sketch('plan'):''}<dl class="kv"><dt>건축물</dt><dd>예시 주민회관 · 본동</dd><dt>자료 출처</dt><dd>가상 예시 자료</dd><dt>기준일</dt><dd>2026.09.15</dd><dt>연결 상태</dt><dd>동·점검건 식별정보 확인</dd></dl><p class="muted">실제 파일이나 외부 API를 호출하지 않는 시안입니다.</p>`);}
pages.field=()=>caseHead('field')+steps(1)+`<section class="panel"><div class="bar"><div><h2>현장조사·결함 근거</h2><p class="muted">위치와 점검항목 중 편한 기준으로 같은 증거를 찾습니다. 예시 항목 3건.</p></div><div class="actions">${btn('항목 기준',"fieldMode='항목 기준';go('field')",fieldMode==='항목 기준'?'active':'')}${btn('층·공간 기준',"fieldMode='층·공간 기준';go('field')",fieldMode==='층·공간 기준'?'active':'')}</div></div>${!state.evidence?`<div class="notice"><strong>확인할 자료 1건</strong>옥상 난간의 현장 위치와 사진 설명을 확인해 주세요. ${btn('확인 항목 열기',"selectedDefect='F-03';go('defect')",'mini')}</div>`:`<div class="notice blue">예시 현장 근거 3건을 확인했습니다. 관찰값과 판단을 바꾸지 않고 확인 상태만 반영했습니다.</div>`}<div class="tablebox"><table><thead><tr><th>${fieldMode==='항목 기준'?'점검 기준·항목':'층·공간·부재'}</th><th>${fieldMode==='항목 기준'?'현장 위치':'연결된 점검항목'}</th><th>관찰 내용</th><th>자료 상태</th><th>상세</th></tr></thead><tbody>${defects.map(d=>`<tr><td>${fieldMode==='항목 기준'?d.item:`${d.place} · ${d.part}`}</td><td>${fieldMode==='항목 기준'?`${d.place} · ${d.part}`:d.item}</td><td>${d.kind}<small>${d.value}</small></td><td>${chip(d.id==='F-03'?(state.evidence?'근거 확인됨':'설명 확인 필요'):d.status,d.id==='F-03'&&!state.evidence?'warn':'')}</td><td>${btn('근거 열기',`selectedDefect='${d.id}';go('defect')`,'mini')}</td></tr>`).join('')}</tbody></table></div><details><summary>사진·위치로 보기</summary><div class="thumbs">${defects.map((d,i)=>`<button onclick="selectedDefect='${d.id}';go('defect')">${sketch(i===2?'roof':'wall')}<p>${d.id} · ${d.place} · ${d.part}</p></button>`).join('')}</div></details><div class="pageactions">${btn('현장 준비',"go('prep')")}<button class="primary" ${state.evidence?'':'disabled'} onclick="finishField()">이번 회차 자료 확인 마침</button></div><p class="reviewnote">‘자료 확인’은 법정 점검 완료나 안전등급 확정을 뜻하지 않습니다. 실제 현장 입력·사진 첨부는 기존 SSIB 기능을 활용하는 구성입니다.</p></section>`;
pages.defect=()=>{const d=defects.find(x=>x.id===selectedDefect)||defects[2];return caseHead('field')+`<div class="bar"><h2>${d.id} · ${d.place} · ${d.part}</h2>${btn('결함 목록',"go('field')")}</div><div class="grid"><section class="panel"><h3>현장 근거</h3>${sketch(d.id==='F-03'?'roof':'wall')}<p class="muted">근거 ID: ${d.id}-PHOTO-01 · 이번 회차 · 2026.09.10</p><div class="tabs">${btn('이전 회차 비교',"go('history')")}${btn('3D·부재 위치',"showSource('BIM')")}</div><dl class="kv"><dt>점검 위치</dt><dd>${d.place} · ${d.part}</dd><dt>관찰 내용</dt><dd>${d.value}</dd><dt>자료 성격</dt><dd>현장 관찰 예시 · AI 추정과 구분</dd></dl></section><section class="panel"><h3>보고서와 연결된 항목</h3><p>${d.item}</p><p>이 근거는 같은 점검건의 해당 세부항목에서 다시 확인할 수 있습니다.</p><label for="evidence-caption">현장 위치 설명</label><textarea id="evidence-caption">${esc(state.captions[d.id]||(d.id==='F-03'?'[가상 예시] 옥상 난간 촬영 위치 기록입니다.':'[가상 예시] 해당 층의 위치와 부재를 확인할 수 있도록 관찰 지점을 표시한 자료입니다.'))}</textarea><div class="checkline"><input id="evidence-check" type="checkbox" ${state.evidence?'checked':''} onchange="document.querySelector('#confirm-evidence').disabled=!this.checked"><label for="evidence-check">선택한 위치와 연결된 점검항목을 확인했습니다.</label></div><button id="confirm-evidence" class="primary" ${state.evidence?'':'disabled'} onclick="confirmEvidence()">확인 내용 반영</button><p class="reviewnote">여기서의 반영은 이 브라우저의 가상 작업 상태를 바꿉니다. 실제 사진·판정 데이터는 저장하지 않습니다.</p>${btn('연결된 보고서 항목 보기',"go('report')",'text')}</section></div>`;};
function confirmEvidence(){if(!canEdit())return;if(!$('#evidence-check').checked)return;if(!$('#evidence-caption').value.trim()){toast('위치 설명을 확인해 주세요.');return;}state.captions[selectedDefect]=$('#evidence-caption').value.trim();if(selectedDefect==='F-03')state.evidence=true;state.events.push(`${selectedDefect} 위치·점검항목 연결 확인`);go('field');toast('가상 근거의 확인 상태를 반영했습니다.');}
function finishField(){if(!canEdit())return;if(!state.evidence)return;state.field=true;state.events.push('이번 회차 현장자료 확인 마침');go('report');}
pages.report=()=>caseHead('report')+steps(2)+`<div class="grid"><section class="panel"><div class="bar"><h2>보고서 준비</h2>${chip(`${state.phase==='draft'?'작업본':'공유본'} v${state.version}`,'blue')}</div><p>현장 근거와 의견을 정리한 뒤 공유본을 확인합니다.</p><table><thead><tr><th>확인 항목</th><th>현재 상태</th><th>해당 화면</th></tr></thead><tbody><tr><td>대상·동·회차</td><td>${chip('확인됨','good')}</td><td>${btn('개요',"go('case')",'text')}</td></tr><tr><td>현장 근거 3건</td><td>${chip(state.evidence?'확인됨':'1건 확인 필요',state.evidence?'good':'warn')}</td><td>${btn('근거 확인',"go('field')",'text')}</td></tr><tr><td>현장자료 확인 마침</td><td>${chip(state.field?'완료':'확인 중',state.field?'good':'warn')}</td><td>${btn('현장자료',"go('field')",'text')}</td></tr><tr><td>종합 의견</td><td>${chip(state.opinion?'정리됨':'작성 필요',state.opinion?'good':'warn')}</td><td>아래 의견 영역</td></tr></tbody></table><div class="notice blue"><strong>현재 화면은 보고 준비를 돕습니다.</strong>세부 점검표·산정 규칙은 해당 업무의 기존 SSIB 양식을 사용합니다. 자료 준비 상태를 법정 제출 가능 여부와 동일하게 표시하지 않습니다.</div><div class="actions">${btn('연결된 현장 근거',"go('field')")}${btn('현재 보고서 미리보기',"go('preview')")}</div></section><section class="panel"><h2>종합 의견</h2><label for="opinion">이번 회차 관찰 결과의 정리</label><textarea id="opinion" placeholder="가상 의견을 확인하거나 입력할 수 있습니다.">${esc(state.opinion)}</textarea><div class="actions">${btn('의견 정리 반영','saveOpinion()','primary')}${btn('가상 예시문 보기','showOpinionExample()','text')}</div><details><summary>의견에 연결되는 근거</summary><p>F-01 · 계단실 벽 / F-02 · 복도 천장 / F-03 · 옥상 난간</p>${btn('근거 목록 열기',"go('field')",'mini')}</details><div class="pageactions">${btn('업무 요약',"go('case')")}<button class="primary" ${state.field&&state.opinion?'':'disabled'} onclick="go('share')">공유 전 확인</button></div><p class="reviewnote">가상 작성본은 이 브라우저에 보관합니다. 실제 서버 저장·다운로드·외부 제출은 실행하지 않습니다.</p></section></div>`;
function showOpinionExample(){if(!canEdit())return;modal('가상 의견 예시',`<p>${demoOpinion}</p><p class="muted">예시 내용을 작업본에 넣고 확인할 수 있습니다. 실제 기술적 판단을 제시하는 문구가 아닙니다.</p>${btn('예시문을 작업본에 넣기',"document.querySelector('#dialog').close();document.querySelector('#opinion').value=demoOpinion",'primary')}`);}
function saveOpinion(){if(!canEdit())return;const value=$('#opinion').value.trim();if(!value){toast('의견 내용을 확인해 주세요.');return;}if(state.phase!=='draft'){toast('공유본은 보존됩니다. 보완 요청이 있으면 보완 응답에서 새 버전으로 정리합니다.');return;}state.opinion=value;state.events.push('작업본 종합 의견 정리');go('report');toast('가상 작업본에 의견을 반영했습니다.');}
pages.preview=()=>caseHead('report')+`<div class="bar"><h2>보고서 미리보기 · v${state.version}</h2><div class="actions">${btn('준비 상태 확인',"go('report')")}${btn('공유·검토 상태',`go('${role==='official'?'review':'shared'}')`)}</div></div><article class="reportpaper"><div class="eyebrow" style="text-align:center">가상 보고서 · 주요 항목 발췌</div><h2>소규모 노후건축물 점검결과</h2><div class="rpttitle">예시 주민회관 · 본동<br>2026년 2회차 · v${state.version}</div><dl class="kv"><dt>점검일</dt><dd>2026.09.10</dd><dt>작성기관</dt><dd>예시 B점검기관</dd><dt>주소</dt><dd>예시시 안전로 20</dd></dl><h3>1. 현장 관찰 근거</h3><table><thead><tr><th>위치·부재</th><th>관찰자료</th><th>근거 ID</th></tr></thead><tbody>${defects.map(d=>`<tr><td>${d.place} · ${d.part}</td><td>${d.value}</td><td>${d.id}-PHOTO-01</td></tr>`).join('')}</tbody></table><h3 style="margin-top:25px">2. 종합 의견</h3><p>${state.opinion?esc(state.opinion):'의견 작성 전입니다.'}</p>${state.reply?`<h3>3. 보완 응답</h3><p>${esc(state.reply)}</p>`:''}<div class="notice">플랫폼 내 결과 공유용 시안입니다. 법정 보고서 제출·접수·승인 상태는 이 미리보기에서 확정하지 않습니다.</div></article>`;
pages.share=()=>caseHead('report')+steps(3)+`<section class="panel" style="max-width:920px"><h2>결과 공유 전 확인</h2><p>현재 작업본을 v1 공유본으로 남기고 관할 담당자의 자료 검토 흐름으로 연결합니다.</p><dl class="kv"><dt>업무 건</dt><dd>예시 주민회관 · 본동 / 2026년 2회차</dd><dt>공유 자료</dt><dd>보고서 v1 · 현장 근거 3건 · 종합 의견</dd><dt>검토 담당</dt><dd>예시시 건축안전 담당</dd><dt>현장자료</dt><dd>${state.field?'확인 완료':'확인 필요'}</dd><dt>법정 처리</dt><dd>BLCM 별도 확인</dd></dl><div class="notice blue">공유 이후 수정이 필요한 내용은 새 버전으로 남겨, 검토한 원문과 변경 이력을 보존합니다.</div><div class="checkline"><input id="share-check" type="checkbox" onchange="document.querySelector('#share-confirm').disabled=!(this.checked&&state.field&&state.opinion)"><label for="share-check">대상·회차·공유할 버전을 확인했습니다.</label></div><div class="pageactions">${btn('미리보기',"go('preview')")}<button id="share-confirm" class="primary" disabled onclick="shareReport()">v1 결과 공유</button></div><p class="reviewnote">내부 결과 공유·검토는 신규 협업 흐름의 가정입니다. 실제 시스템에 요청이나 메시지를 전송하지 않습니다.</p></section>`;
function shareReport(){if(!canEdit())return;if(!state.field||!state.opinion||!$('#share-check')?.checked)return;state.phase='shared';state.snapshots=[{version:1,opinion:state.opinion,note:'최초 공유본',captions:{...state.captions}}];state.events.push('v1 결과 공유 · 예시 B점검기관 → 예시시');go('shared');}
pages.shared=()=>caseHead('report')+`<section class="panel">${state.phase==='draft'?'':'<div class="success">✓</div>'}<h2>${state.phase==='draft'?'아직 결과를 공유하지 않았습니다.':'v'+state.version+' 결과 공유 상태'}</h2><p>${state.phase==='draft'?'보고서의 확인 항목을 마친 후 공유할 수 있습니다.':'공유한 버전과 담당자의 검토 상태를 확인할 수 있습니다.'}</p><dl class="kv"><dt>현재 상태</dt><dd>${stageName()}</dd><dt>공유본</dt><dd>${state.snapshots.length?state.snapshots.map(x=>'v'+x.version).join(', '):'공유 전'}</dd><dt>법정 처리</dt><dd>${chip('BLCM 별도 확인')}</dd></dl><div class="actions">${btn('업무 홈',"go('home')")}${btn('공유 이력',"go('history')")}${state.phase==='draft'?btn('보고서 준비',"go('report')",'primary'):''}</div><p class="annotation">시안 이어보기: 아래 고정 바의 ‘공무원 검토로 이어보기’를 누르면 같은 공유본을 검토하는 다음 담당자의 화면으로 이동합니다.</p></section>`;

pages.review=()=>{
if(state.phase==='complete')return pages.complete();
if(state.phase==='draft')return caseHead('case')+`<section class="panel"><h2>기관의 자료 준비 중</h2><p>아직 공유된 검토본이 없습니다. 기관이 자료를 공유한 뒤 해당 버전을 확인할 수 있습니다.</p>${btn('현재 준비 상태',"go('case')")}</section>`;
if(state.phase==='requested')return pages.requested();
const revised=state.phase==='resubmitted';return caseHead('report')+steps(4)+`<div class="grid"><section class="panel"><div class="bar"><div><h2>${revised?'보완된':'공유된'} v${state.version} 검토</h2><p class="muted">검토할 버전과 연결된 근거를 확인합니다.</p></div>${btn('보고서 미리보기',"go('preview')")}</div>${revised?`<div class="notice blue"><strong>변경된 내용 1건</strong>F-03 옥상 난간 · 사진 위치 설명 보완</div><h3>요청한 내용</h3><p>${esc(state.request)}</p><h3>기관의 답변</h3><p>${esc(state.reply)}</p><p>${chip('기관 답변 완료','good')} ${chip('담당자 확인 필요','warn')}</p>`:`<h3>보고서 요약</h3><p>${esc(state.opinion)}</p><h3 style="margin-top:22px">검토할 근거</h3><table><thead><tr><th>항목</th><th>연결된 근거</th><th>보기</th></tr></thead><tbody>${defects.map(d=>`<tr><td>${d.item}</td><td>${d.id}-PHOTO-01</td><td>${btn('열기',`showReviewEvidence('${d.id}')`,'mini')}</td></tr>`).join('')}</tbody></table>`}<div class="actions" style="margin-top:15px">${btn('F-03 현장 위치와 근거',"showReviewEvidence('F-03')")}${revised?btn(`원본 v1과 보완본 v${state.version}`,"showVersions()") :btn('지난 회차 비교',"go('history')")}</div></section><section class="panel"><h2>검토 결과</h2><dl class="kv"><dt>검토 대상</dt><dd>보고서 v${state.version}</dd><dt>담당 역할</dt><dd>예시시 건축안전 담당</dd><dt>현재 단계</dt><dd>${stageName()}</dd><dt>외부 처리</dt><dd>BLCM 별도 확인</dd></dl><div class="checkline"><input id="review-check" type="checkbox" ${state.reviewChecked?'checked':''} onchange="state.reviewChecked=this.checked;document.querySelector('#complete-review').disabled=!this.checked"><label for="review-check">공유본${revised?'과 보완 응답':''} 및 관련 근거를 확인했습니다.</label></div><div class="actions"><button id="complete-review" class="primary" ${state.reviewChecked?'':'disabled'} onclick="completeReview()">결과 검토 완료</button>${revised?btn('추가 보완 흐름 안내','showFurtherReview()'):btn('보완 요청 작성',"go('supplement_request')")}</div><div class="notice">‘결과 검토 완료’는 이 플랫폼의 자료 검토 상태입니다. 법정 접수·승인이나 건축물 안전 확정으로 표시하지 않습니다.</div></section></div>`;
};
function showReviewEvidence(id){const d=defects.find(x=>x.id===id);modal(`${id} · ${d.place} · ${d.part}`,`${sketch(id==='F-03'?'roof':'wall')}<p><strong>보고서 항목</strong> ${d.item}</p><p><strong>근거 ID</strong> ${id}-PHOTO-01 · v${state.version}와 연결</p><p>${id==='F-03'&&state.reply?esc(state.reply):esc(state.captions[id]||'현장 위치·촬영 시점·관찰 내용을 같은 근거에서 확인합니다.')}</p>`);}
pages.supplement_request=()=>caseHead('report')+`<section class="panel" style="max-width:1000px"><div class="eyebrow">공무원 → 전문기관</div><h2>항목별 보완 요청</h2><dl class="kv"><dt>검토한 원문</dt><dd>보고서 v${state.version} · 원문 보존</dd><dt>보완 항목</dt><dd>F-03 · 옥상 난간의 현장 위치 설명</dd><dt>연결된 근거</dt><dd>F-03-PHOTO-01</dd><dt>응답 일정</dt><dd>2026.09.22 · 협의 일정 예시</dd></dl><label for="request-text">확인할 내용과 보완 이유</label><textarea id="request-text">[가상 보완 요청] 옥상 난간 사진이 어느 구간을 촬영했는지 확인할 수 있도록 출입구 기준의 위치 설명을 보완해 주세요. 관련 점검항목과 같은 근거 ID에 연결해 주세요.</textarea><div class="notice blue">요청 내용은 해당 보고서 버전·점검항목·근거와 연결됩니다. 기관은 이 요청을 보고 새 버전으로 응답합니다.</div><div class="pageactions">${btn('검토 화면',"go('review')")}${btn('보완 요청 확정','requestCorrection()','primary')}</div><p class="reviewnote">가상 흐름 안에서만 요청 상태가 바뀝니다. 실제 담당자에게 메시지를 전송하지 않습니다.</p></section>`;
function showFurtherReview(){modal('추가 보완이 필요한 경우','<p>실제 운영에서는 새 요청을 검토 버전·항목에 연결하고, 이전 요청과 답변을 보존한 채 다음 수정본을 만드는 구조가 필요합니다.</p><p>이 가상 시안은 최초 공유본 v1에서 한 차례 보완한 v2를 재검토하는 대표 흐름을 구현했습니다.</p>');}
function requestCorrection(){if(role!=='official'||state.phase!=='shared'){toast('이 시안은 v1 요청부터 v2 재검토까지 한 차례 보완을 제공합니다.');return;}const value=$('#request-text').value.trim();if(!value){toast('보완 이유와 요청 내용을 확인해 주세요.');return;}state.request=value;state.phase='requested';state.reviewChecked=false;state.events.push(`v${state.version}의 F-03 보완 요청 · 예시시 → 예시 B점검기관`);go('requested');}
pages.requested=()=>caseHead('report')+`<section class="panel"><h2>보완 요청 내용과 응답 현황</h2><p>${chip('기관 응답 대기','warn')} · 보고서 v${state.version}의 F-03</p><div class="notice"><strong>요청 내용</strong>${esc(state.request||'요청 내용 예시가 아직 없습니다.')}</div><dl class="kv"><dt>원문</dt><dd>공유본 v${state.version} 보존</dd><dt>응답 일정</dt><dd>2026.09.22</dd><dt>기관 응답</dt><dd>응답 전</dd><dt>담당자 확인</dt><dd>응답 후 확인</dd></dl><div class="actions">${btn('업무 홈',"go('home')")}${btn('이력 보기',"go('history')")}</div><p class="annotation">하단의 ‘기관 보완 응답으로 이어보기’를 누르면 요청을 받은 전문기관의 화면으로 전환됩니다.</p></section>`;
pages.reply=()=>caseHead('report')+steps(4)+`<div class="grid"><section class="panel"><div class="eyebrow">보완 요청 1건</div><h2>v${state.version}의 요청 항목 확인</h2><p>${chip('F-03 옥상 난간','warn')}</p><p>${esc(state.request||'[가상 보완 요청] 옥상 난간 사진의 촬영 위치를 보완해 주세요.')}</p><dl class="kv"><dt>요청 담당</dt><dd>예시시 건축안전 담당</dd><dt>대상 버전</dt><dd>공유본 v${state.version}</dd><dt>근거</dt><dd>F-03-PHOTO-01</dd></dl>${sketch('roof')}${btn('원문 보기',"showVersions()",'text')}</section><section class="panel"><h2>보완 응답 · v${state.version+1} 작업본</h2><label for="reply-text">보완한 내용</label><textarea id="reply-text">${esc(state.reply||'[가상 보완 답변] F-03-PHOTO-01은 옥상 출입구에서 우측 난간 구간을 바라본 위치입니다. 위치 도식과 점검항목의 근거 설명을 같은 ID로 연결했습니다. 관찰 측정값은 변경하지 않았습니다.')}</textarea><div class="checkline"><input id="reply-check" type="checkbox" onchange="document.querySelector('#submit-reply').disabled=!this.checked"><label for="reply-check">요청 항목과 답변·관련 근거의 연결을 확인했습니다.</label></div><div class="notice blue">이전 공유본은 보존합니다. 이번 응답은 v${state.version+1}로 공유되고, 공무원의 확인이 끝날 때까지 ‘기관 답변 완료’로 표시합니다.</div><div class="pageactions">${btn('이력',"go('history')")}<button id="submit-reply" class="primary" disabled onclick="submitReply()">v${state.version+1} 보완 결과 공유</button></div></section></div>`;
function submitReply(){if(role!=='agency'||state.phase!=='requested'){toast('기관의 보완 요청 단계에서 응답할 수 있습니다.');return;}const value=$('#reply-text').value.trim();if(!value||!$('#reply-check').checked){toast('답변 내용과 연결된 근거를 확인해 주세요.');return;}state.reply=value;state.captions['F-03']=value;state.version+=1;state.phase='resubmitted';state.reviewChecked=false;state.snapshots.push({version:state.version,opinion:state.opinion,note:state.reply,captions:{...state.captions}});state.events.push(`v${state.version} 보완 결과 공유 · F-03 위치 설명 · 기관 답변 완료`);go('resubmitted');}
pages.resubmitted=()=>caseHead('report')+`<section class="panel"><div class="success">✓</div><h2>v${state.version} 보완 결과를 공유했습니다</h2><p>${chip('기관 답변 완료','good')} ${chip('공무원 확인 대기','warn')}</p><p>공무원은 요청한 항목과 v${state.version}의 답변·변경 내용을 함께 확인할 수 있습니다.</p><dl class="kv"><dt>보존한 원문</dt><dd>${state.snapshots.slice(0,-1).map(x=>'v'+x.version).join(', ')}</dd><dt>새 공유본</dt><dd>v${state.version} · F-03 위치 설명 보완</dd><dt>BLCM 처리</dt><dd>별도 확인</dd></dl><div class="actions">${btn('버전 비교',"showVersions()")}${btn('내 업무',"go('home')")}</div><p class="annotation">하단의 ‘공무원 재검토로 이어보기’에서 다음 담당자의 확인 화면을 볼 수 있습니다.</p></section>`;
function completeReview(){if(role!=='official'||!['shared','resubmitted'].includes(state.phase)||!state.reviewChecked){toast('공유본과 근거를 확인한 뒤 검토를 마칠 수 있습니다.');return;}state.phase='complete';state.events.push(`v${state.version} 결과 검토 완료 · 예시시 담당자`);go('complete');}
pages.complete=()=>caseHead('report')+steps(5)+`<section class="panel"><div class="success">✓</div><h2>플랫폼 결과 검토 완료</h2><p>예시 주민회관 · 본동 / 2026년 2회차 / 검토한 공유본 v${state.version}</p><div class="statusgrid"><div><small>기관</small>결과·근거 공유</div><div><small>공무원</small>결과 검토 완료</div><div><small>버전 이력</small>${state.snapshots.map(x=>'v'+x.version).join(' → ')||'공유본 확인'}</div><div><small>BLCM 법정 처리</small>별도 확인</div></div><h3>이후 별도로 확인할 업무</h3><table><thead><tr><th>확인할 내용</th><th>담당 범위</th><th>상태</th></tr></thead><tbody><tr><td>원천 시스템의 법정 처리 여부</td><td>실제 연계·운영 절차에 따름</td><td>${chip('별도 확인','warn')}</td></tr><tr><td>차기 점검·추적 일정</td><td>해당 업무의 일정 관리</td><td>${chip('일정 확인 필요')}</td></tr></tbody></table><div class="notice blue">이번 자료의 검토 종료를 표시합니다. 건축물의 모든 안전문제 해소, 법정 승인, 후속조치 완료로 확대해서 표시하지 않습니다.</div><div class="actions">${btn('처리 이력 보기',"go('history')",'primary')}${btn('업무 홈으로',"go('home')")}${role==='official'?btn('관할 후보로 돌아가기',"go('candidate')"):''}</div></section>`;
pages.history=()=>caseHead('history')+`<div class="grid"><section class="panel"><h2>동일 위치의 이전 회차 비교</h2><p class="muted">2025년 1회차 → 2026년 2회차 · 관찰값 예시</p><table><thead><tr><th>위치·부재</th><th>이전 회차</th><th>이번 회차</th><th>해석에 필요한 확인</th></tr></thead><tbody>${defects.map(d=>`<tr><td>${d.place} · ${d.part}</td><td>${d.before}</td><td>${d.id==='F-03'&&!state.evidence?'이번 회차 근거 미확인':d.value}</td><td>${d.id==='F-03'?'자료 없음과 보수 완료 구분':'촬영 위치·측정 조건 확인'}</td></tr>`).join('')}</tbody></table><div class="notice">숫자 차이만으로 호전·악화를 자동 확정하지 않습니다. 비교 기준과 근거 상태를 함께 확인합니다.</div><div class="actions">${btn('관련 사진·근거',"showReviewEvidence('F-01')")}${btn('보고서 버전 확인',"showVersions()")}</div></section><section class="panel"><h2>이번 업무의 처리 이력</h2>${timeline()}<p class="muted">업무 건과 공유 버전을 기준으로 인계 내용을 남깁니다.</p></section></div>`;
function showVersions(){modal('공유본 버전과 변경 이력',state.snapshots.length?state.snapshots.map(s=>`<section class="panel compact"><h3>v${s.version} ${s.version===1?'최초 공유본':'보완 공유본'}</h3><p>${esc(s.opinion)}</p><p><strong>변경·공유 내용</strong> ${esc(s.note)}</p><p><strong>F-03 근거 설명</strong> ${esc(s.captions?.['F-03']||(s.version===1?'[가상 예시] 옥상 난간 촬영 위치 기록입니다.':s.note))}</p></section>`).join(''):'<p>아직 공유한 버전이 없습니다. 보고서 준비 후 공유본을 만들 수 있습니다.</p>');}

pages.reports=()=>`<div class="bar"><div><h1>점검결과·보고서</h1><p class="muted">먼저 확인할 건축물·회차를 선택합니다. 조회범위: ${role==='official'?'관할':'내 기관 담당·공유 건'}</p></div></div><section class="panel"><table><thead><tr><th>건축물·동 / 회차</th><th>보고서 상태</th><th>공유·검토</th><th>보기</th></tr></thead><tbody><tr><td>예시 주민회관 · 본동<br>소규모 노후건축물 점검 · 2026년 2회차</td><td>${state.opinion?'의견 정리됨':'의견 작성 필요'}</td><td>${stageName()}</td><td>${btn('보고서 열기',"go('report',{id:2})",'primary mini')}</td></tr><tr><td>예시 중앙상가 · 가동<br>정기점검 · 3회차</td><td>원천 자료 확인 필요</td><td>작성 현황 확인</td><td>${btn('해당 업무 확인','openCase(1)','mini')}</td></tr></tbody></table></section>`;
pages.histories=()=>`<div class="bar"><div><h1>노후건축물·점검 이력</h1><p class="muted">건축물과 동을 고른 뒤 업무별 회차를 확인합니다.</p></div></div><section class="panel"><table><thead><tr><th>건축물·동</th><th>업무유형</th><th>비교할 회차</th><th>보기</th></tr></thead><tbody><tr><td>예시 주민회관 · 본동</td><td>소규모 노후건축물 점검</td><td>2025년 1회차 / 2026년 2회차</td><td>${btn('회차·버전 이력 열기',"go('history',{id:2})",'primary mini')}</td></tr><tr><td>예시 중앙상가 · 가동</td><td>정기점검</td><td>3회차 · 원천 기록 확인</td><td>${btn('업무 개요','openCase(1)','mini')}</td></tr></tbody></table></section>`;
pages.region=()=>`<div class="bar"><div><div class="eyebrow">관할 전체를 보는 업무</div><h1>관할 현황·대상 선별</h1><p class="muted">조회범위: 예시시 · 예시 후보 2건 · 자료 기준일 2026.09.15</p></div>${btn('내 업무',"go('home')")}</div><div class="notice blue">지도에서 분포를 확인하고, 후보의 근거와 기존 점검이력을 함께 검토합니다. 선별 후보는 현장 진단 결과나 법정 안전등급을 뜻하지 않습니다.</div><div class="grid"><section class="panel mapbox"><h2>후보 분포</h2><svg viewBox="0 0 580 380" role="img" aria-label="예시시의 두 후보 건축물 위치를 나타낸 가상 지도"><rect width="580" height="380" fill="#edf1f5"/><path d="M0 100H580M0 240H580M130 0V380M330 0V380M500 0V380" stroke="white" stroke-width="24"/><path d="M0 330Q170 220 310 310T580 220" fill="none" stroke="#bedbec" stroke-width="35"/><g fill="#d7e1e9" stroke="#bbccd9"><rect x="25" y="25" width="70" height="45"/><rect x="175" y="25" width="115" height="45"/><rect x="370" y="138" width="95" height="64"/><rect x="180" y="140" width="85" height="60"/></g><g><circle cx="220" cy="165" r="20" fill="#bf722d"/><text x="214" y="172" fill="white" font-size="20">1</text><text x="156" y="212" font-size="15" fill="#395571">예시 주민회관</text><circle cx="408" cy="60" r="20" fill="#bf722d"/><text x="402" y="67" fill="white" font-size="20">2</text><text x="350" y="105" font-size="15" fill="#395571">예시 문화시설</text></g><text x="20" y="365" font-size="12" fill="#657f93">설명용 가상 지도 · 실제 좌표·지도 서비스 아님</text></svg><div class="actions">${btn('① 주민회관 후보 확인',"go('candidate')",'primary')}${btn('② 문화시설 자료 확인',"go('data')")}</div></section><section class="panel"><h2>같은 조건의 후보 목록 · 2건</h2><table><thead><tr><th>후보 건축물·동</th><th>확인할 이유</th></tr></thead><tbody><tr><td>${btn('예시 주민회관 · 본동',"go('candidate')",'text')}</td><td>이전 관찰기록 있음<br>이번 회차 자료 ${state.phase==='complete'?'검토 완료':'확인 중'}</td></tr><tr><td>${btn('예시 문화시설 · 나동',"go('data')",'text')}</td><td>대장 연결 확인 필요<br>선별 근거 확정 전</td></tr></tbody></table><h3 style="margin-top:24px">선별 근거를 읽는 방법</h3><p>출처·기준일·관측자료 유무를 먼저 확인합니다. 점수나 색상만으로 건축물의 안전 여부를 단정하지 않습니다.</p><p class="muted">실제 조건 조회·AI 추천·후보 산출은 실행하지 않습니다. 이 화면은 지도에서 업무로 이어지는 구조를 보여줍니다.</p></section></div>`;
pages.candidate=()=>`<div class="breadcrumb">${btn('관할 현황·대상 선별',"go('region')",'text')} / 후보 검토</div><section class="casehead"><div class="eyebrow">관할 선별 후보 · 예시 1 / 2</div><h1>예시 주민회관 · 본동</h1><p>예시시 안전로 20 · 관련 업무: 소규모 노후건축물 점검</p></section><div class="grid"><section class="panel"><h2>후보로 확인하는 이유</h2><dl class="kv"><dt>확인 근거</dt><dd>이전 회차 관찰기록과 이번 회차 현장자료 대조 필요</dd><dt>자료 출처</dt><dd>예시 점검기록 · 기준일 2026.09.15</dd><dt>최근 점검</dt><dd>2026년 2회차 · ${stageName()}</dd><dt>불확실한 정보</dt><dd>후속 현장확인 필요 여부 · 원천 시스템 처리 상태</dd><dt>현재 해석</dt><dd>검토 후보 · 법정 안전등급 판정 아님</dd></dl><div class="actions">${btn('관련 점검건 열기',"openCase(2)",'primary')}${btn('이전 회차 근거',"go('history',{id:2})")}</div>${state.phase==='complete'?`<div class="notice blue"><strong>연결된 점검자료의 검토가 끝났습니다.</strong>후보 제외나 보수 완료 여부는 별도 판단입니다. 결과와 후속 확인사항을 읽고 다음 대상을 정합니다.</div>`:''}</section><section class="panel"><h2>후속 확인 계획</h2><p>연결된 점검건이 있으므로 그 자료부터 확인합니다. 같은 건을 다시 만드는 중복을 줄입니다.</p><div class="checkline"><input id="candidate-check" type="checkbox" ${candidateChoice?'checked':''} onchange="candidateChoice=this.checked;document.querySelector('#candidate-confirm').disabled=!this.checked"><label for="candidate-check">기존 점검 결과와 차기 현장확인 필요 여부를 대조할 후보로 표시</label></div><button id="candidate-confirm" ${candidateChoice?'':'disabled'} onclick="markCandidate()">후속 확인 후보에 표시</button>${state.candidate?'<p class="notice blue">가상 후보 표시됨 · 연결된 점검건과 함께 확인합니다.</p>':''}<p class="reviewnote">후보 표시와 후속 업무 연결은 개편 기능의 예시입니다. 실제 대상 선정·점검 지시·통보는 실행하지 않습니다.</p></section></div>`;
function markCandidate(){if(!candidateChoice)return;state.candidate=true;go('candidate');toast('가상 시안에서 후속 확인 후보로 표시했습니다.');}
pages.data=()=>`<div class="bar"><div><h1>연결 확인이 필요한 자료</h1><p class="muted">업무 담당자가 확인할 연결 상태와 데이터 운영자의 처리 경로를 구분합니다.</p></div>${btn('업무 목록',"go('list')")}</div><section class="panel"><h2>예시 문화시설 · 나동</h2><dl class="kv"><dt>업무 건</dt><dd>3종건축물 지정 실태조사 · 2026년 1회차</dd><dt>확인할 문제</dt><dd>현재 자료의 동 식별정보와 대장 연결 미확인</dd><dt>업무에 미치는 영향</dt><dd>건축물의 대장 정보와 조사자료가 같은 동인지 확인 필요</dd><dt>사용 가능한 자료</dt><dd>업무 목록 · 기존 조사기록</dd><dt>담당 경로</dt><dd>데이터 연결 담당자가 후보·원천정보를 확인</dd></dl><div class="notice"><strong>자료가 연결되지 않았다고 점검기록까지 없는 것은 아닙니다.</strong>자료 종류별 상태를 확인하고, 기존 기록을 보면서 연결 문제를 해결할 수 있게 구성합니다.</div><div class="actions">${btn('대장 연결 후보 보기','showMatchCandidates()')}${btn('기존 조사 업무 보기','openCase(3)','primary')}</div><p class="reviewnote">현행 관리자 화면에 미연결 목록, 대장·허브·직접 키 입력 등의 복구 기능이 이미 있습니다. 이를 업무 위치에서 이해하고 찾아갈 수 있도록 연결하는 제안입니다.</p></section><section class="panel"><h2>주민회관 점검건의 자료 상태</h2><table><thead><tr><th>자료</th><th>확인 상태</th><th>확인 경로</th></tr></thead><tbody><tr><td>현장 관찰·사진</td><td>${state.evidence?'근거 확인됨':'설명 1건 확인 필요'}</td><td>${btn('현장자료',"go('field',{id:2})",'text')}</td></tr><tr><td>BIM</td><td>연결됨 · 보조 열람</td><td>${btn('모델을 못 열 때 안내','showBimFallback()','text')}</td></tr><tr><td>BLCM 법정 처리</td><td>별도 확인 · 자동 갱신 근거 미확인</td><td>원천 기록과 운영 절차 대조</td></tr></tbody></table></section>`;
function showMatchCandidates(){modal('대장 연결 후보 확인',`<p>가상 후보 1건: 예시 문화시설 · 나동 / 예시시 문화로 30</p><dl class="kv"><dt>대조할 항목</dt><dd>주소 · 동 구분 · 대장 식별정보 · 원천 자료 기준일</dd><dt>처리 상태</dt><dd>데이터 연결 담당자 확인 필요</dd></dl><p>현재 복구 기능을 재활용하는 구성입니다. 시안에서는 연결을 저장하거나 키를 변경하지 않습니다.</p>`);}
function showBimFallback(){modal('모델 열람이 어려운 경우',`<p>같은 점검건의 사진·위치 설명·보고서를 계속 확인할 수 있습니다.</p><p class="muted">모델 미확보, 로딩 지연, 파일 연결 오류는 각각 표시하고 데이터 담당자에게 확인할 경로를 제공합니다.</p>${btn('현장 근거 이어보기',"document.querySelector('#dialog').close();go('field',{id:2})",'primary')}`);}

const explanations={
login:['로그인','현행은 홍보·서비스 소개 비중이 크고, 아이디 표기와 이메일 예시가 함께 보입니다.','업무 이용자는 어떤 계정으로 들어가고 로그인 후 무엇을 할 수 있는지 먼저 알고 싶습니다.','업무 계정 안내와 소속·역할 확인 경로를 분명히 하고, 로그인 후 담당 업무로 연결합니다.','첫 진입의 혼동을 줄입니다. 실제 운영의 역할은 계정 권한으로 결정하고 매번 선택하게 하지 않습니다.','01_login'],
first:['최초 이용 안내','최초 이용자와 이미 권한을 받은 이용자의 필요가 다릅니다.','매번 소속 선택이나 안내를 거치면 반복 업무가 늦어집니다.','최초 소속·권한 확인을 별도 경로로 안내하고 확인된 계정은 바로 업무 홈으로 보냅니다.','계정 문제와 업무 시작을 구분할 수 있습니다. 승인 절차의 상세 운영은 추가 확인 사항입니다.'],
home:['역할별 메인화면','현행 첫 화면은 지도이며, 업무 목록은 별도 플랫폼 전환과 관리자 메뉴를 통해 들어갑니다.','담당자가 오늘 처리할 건을 보려면 먼저 기능과 검색조건을 찾아야 합니다.','공무원은 관할 유형별 확인 업무, 전문기관은 담당 점검과 보고서의 남은 일을 먼저 봅니다.','익숙한 업무 이름으로 바로 시작합니다. 지도는 관할 선별 업무에서 계속 사용합니다.','39_admin_dashboard'],
list:['업무 목록','현행 업무별 목록·필터는 이미 있지만, 일부 화면은 큰 검색 영역과 많은 열이 결과를 밀어냅니다.','노트북에서 첫 건만 보이거나 오른쪽 내용을 보려고 가로로 움직여야 합니다.','기본 필터와 핵심 다섯 열을 먼저 보이고, 세부 정보는 선택한 업무 건에서 확인합니다.','대상·유형·회차·일정·다음 행동을 한 번에 읽고 올바른 건을 고르기 쉬워집니다.','66_facility3'],
case:['한 점검건의 상세','지도, 관리자, sBIM, SSIB에서 화면 구조와 일부 표시 정보가 달라집니다.','이동할 때 같은 건축물·동·회차인지 다시 확인해야 합니다.','업무 건의 제목과 상태를 위에 유지하고 준비·결함·보고서·이력을 탭으로 연결합니다.','재검색을 줄이고 다른 회차 자료를 잘못 보는 위험을 낮춥니다.','49_inspection_loaded'],
prep:['현장 준비','대장·평면도·BIM·과거 기록은 있으나 각각의 기능에서 찾아보게 됩니다.','현장에 가기 전에 이번 건의 자료가 준비됐는지 모아서 보기 어렵습니다.','같은 건에서 필요한 자료의 출처·연결 상태와 지난 기록을 확인합니다.','자료 누락을 일찍 알고, BIM이 열리지 않아도 다른 근거로 업무를 이어갈 수 있습니다.'],
field:['현장조사·결함','현행 SSIB는 항목/층 기준 및 목록/사진 전환과 결함 상세를 이미 제공합니다.','유용한 현장 기능이 다른 시스템 안에 있어 업무 시작점에서 바로 발견하기 어렵습니다.','기존 조회 방식을 유지하면서 같은 점검건의 현장 탭으로 연결합니다.','새 사용법을 늘리지 않고 현장 위치와 보고서 항목을 오가며 자료를 찾습니다.','102_ssib_defect_list'],
defect:['현장 근거와 점검항목','현행 결함 상세에 위치·항목·측정값·사진 정보가 존재합니다.','보고서 검토와 현장 근거 열람이 분리되면 같은 증거를 다시 찾아야 합니다.','공통 근거 ID와 점검건을 유지해 사진·위치·부재·보고서 항목을 연결합니다.','기관과 공무원이 같은 자료를 보면서 구체적으로 확인하거나 보완할 수 있습니다.'],
report:['보고서 준비','현행 보고서에 미입력 상태와 -점이 표시되고, 미리보기에는 판단 미등록 항목이 보입니다.','다른 화면의 제출·연계 상태만 보면 보고서까지 마친 것으로 오해할 수 있습니다.','남은 자료·의견을 작업 목록으로 보여주고 해당 위치로 이동시킵니다.','무엇을 채워야 하는지 바로 알 수 있습니다. 기존 점검표·산정 규칙은 유지합니다.','56_ssib_report'],
preview:['보고서 미리보기','현재도 보고서 미리보기 기능이 있습니다.','미리보기 자체보다 어느 건·회차·버전이고 준비 상태가 어떤지 연결해서 읽는 것이 중요합니다.','같은 건의 준비 화면, 근거, 공유 버전으로 오갈 수 있도록 구성합니다.','기존 출력 기능을 활용하면서 잘못된 회차나 미완성 문서 공유를 줄입니다.','59_report_preview'],
share:['결과 공유','현재 사이트의 읽기 전용 탐색에서는 기관→공무원의 전체 공유·보완 거래를 확인하지 않았습니다.','누가 어떤 원문을 검토하는지 불분명하면 보완 과정에서 내용이 엇갈립니다.','공유 전에 대상·회차·버전을 확인하고 공유 원문을 보존하는 협업 흐름을 제안합니다.','검토 기준이 되는 문서가 명확해집니다. 신규 기능 가정이며 BLCM 법정 제출을 대신하지 않습니다.'],
review:['공무원 검토','현행에는 결과·사진·비교 자료가 있으나 담당자의 일일 검토 흐름으로 묶인 구조가 약합니다.','기술 화면을 번갈아 열며 무엇을 확인했고 무엇을 요청할지 정리해야 합니다.','공유 버전, 관련 근거, 보완 요청, 검토 결과를 같은 건에서 연결합니다.','담당자가 근거를 보며 확인을 마칠 수 있습니다. 실제 권한·검토 책임은 운영 설계가 필요합니다.'],
supplement_request:['항목별 보완 요청','실제 저장·전송을 하지 않았으므로 현행 보완 거래의 상세 동작은 미검증입니다.','일반적인 자유 메모만 남기면 어떤 문서의 어떤 부분을 고칠지 다시 확인해야 합니다.','검토한 버전·점검항목·근거에 요청 이유를 연결합니다.','기관이 정확한 위치부터 보완할 수 있습니다. 이 화면은 신규 협업 기능 제안입니다.'],
reply:['기관 보완 응답','문서를 고친 결과만 보면 기존 검토본과 수정본이 섞일 수 있습니다.','공무원이 이전에 확인한 내용과 새 답변의 차이를 추적하기 어렵습니다.','v1은 보존하고 요청 항목의 답변을 v2로 공유합니다.','기관의 답변 완료와 공무원의 확인 완료를 구분하고 변경 이유를 남깁니다.'],
complete:['완료 범위와 후속 확인','현장 입력, BIM 연결, 보고서와 외부 처리에는 서로 다른 상태가 있습니다.','하나의 완료 표시로 합치면 안전문제나 법정 처리까지 끝난 것으로 읽힐 수 있습니다.','플랫폼 자료 검토 완료를 정확히 표시하고 BLCM 처리·후속 일정은 별도로 남깁니다.','현재 끝난 일과 다음 확인할 일을 구분할 수 있습니다.'],
history:['회차 비교·이력','현행 sBIM에 두 회차의 모델·결함 수치·사진 비교 기능이 있습니다.','숫자 감소나 이번 회차의 빈칸만으로 보수·호전을 판단할 수는 없습니다.','같은 위치의 조건과 근거 유무를 같이 보이고, 보고서 공유 버전과 처리 이력을 연결합니다.','좋은 비교 기능을 유지하면서 자료 없음과 실제 개선을 구분합니다.','98_compare_laptop'],
region:['관할 지도·후보','현행 지도·분야별 선별은 관할지역의 분포를 보는 데 강점이 있습니다.','후보의 색상·점수만 보면 확인 이유나 연결된 기존 점검을 다시 찾아야 합니다.','지도와 같은 조건의 후보 목록, 근거 출처, 기존 점검건을 연결합니다.','지도에서 시작하는 광역 검토도 실제 후속 확인까지 이어집니다.'],
candidate:['후보에서 업무로','후보 정보와 현장 점검 결과가 각 기능에 존재합니다.','이 후보를 이미 점검했는지, 다음에 무엇을 확인할지 맥락이 끊기기 쉽습니다.','기존 점검건과 결과를 먼저 읽고 후속 확인 후보로 이어갑니다.','중복 업무를 줄이며, 결과 검토 완료를 후보 제외·안전 확정과 혼동하지 않습니다.'],
data:['자료 연결 복구','현행 미연결 안내를 누르면 실패 목록과 대장·허브·직접 키 확인 등의 복구 화면이 열립니다.','업무 담당자는 데이터 용어보다 내 업무에 미치는 영향과 확인 경로를 알고 싶습니다.','기존 복구 기능을 재사용하면서 자료 종류별 상태·영향·담당 경로를 설명합니다.','기능을 새로 중복 개발하지 않고 복구 경로를 쉽게 찾습니다.','90_unlinked_records']
};
explanations.reports=explanations.list;explanations.histories=explanations.history;explanations.shared=explanations.share;explanations.requested=explanations.supplement_request;explanations.resubmitted=explanations.reply;
function showExplanation(){const e=explanations[screen]||explanations.case;modal(`${e[0]} — 이렇게 바꾼 이유`,[['현재 관찰',e[1]],['왜 불편한가',e[2]],['제안하는 변화',e[3]],['기대 효과·범위',e[4]]].map(([a,b])=>`<div class="explainrow"><strong>${a}</strong><div>${b}</div></div>`).join('')+`<p><a href="about.html" target="_blank">시안 사용 안내 보기</a></p><p class="muted">관찰된 사실과 새로 제안하는 협업 절차를 구분했습니다. 모든 효과는 사용자 검증이 필요한 설계 가설입니다.</p>`);}
const journey=[['login','로그인','agency'],['first','최초 소속·권한 안내','agency'],['home','기관 메인화면','agency'],['list','담당 점검 목록','agency'],['case','건축물·점검건 상세','agency'],['prep','현장 준비·기존 자료','agency'],['field','현장조사·결함','agency'],['defect','근거·위치·항목 확인','agency'],['report','보고서 준비·남은 항목','agency'],['preview','보고서 미리보기','agency'],['share','공유 전 확인','agency'],['shared','v1 공유 결과','agency'],['home','공무원 메인화면','official'],['review','공유본 v1 검토','official'],['supplement_request','항목별 보완 요청','official'],['requested','보완 요청 현황','official'],['reply','기관 보완 응답','agency'],['resubmitted','v2 보완 결과 공유','agency'],['review','v2 재검토','official'],['complete','결과 검토 완료','official'],['history','버전·회차·처리 이력','official'],['region','관할 지도·후보 목록','official'],['candidate','후보 근거·기존 점검 연결','official'],['data','자료 연결 확인·복구 경로','official']];
function showJourney(){modal('로그인부터 결과 검토까지 · 전체 화면 순서',`<p>처음부터 체험하려면 <strong>기관 담당자로 시작</strong>을 누르세요. 업무가 다른 담당자에게 넘어갈 때만 하단 바에서 역할을 전환합니다.</p><p>${btn('기관 담당자로 처음부터 시작',"document.querySelector('#dialog').close();resetDemo('agency')",'primary')}</p><p class="muted">아래 화면을 선택하면 해당 단계의 가상 상태로 이동합니다. 기존 시안 작업 상태는 초기화됩니다. 실제 데이터를 자동으로 채우는 기능이 아닙니다.</p><div class="journeybuttons">${journey.map((j,i)=>btn(`${String(i+1).padStart(2,'0')}. ${j[1]}`,`jumpTo(${i})`)).join('')}</div>`);}
function resetDemo(r='agency'){role=r;state=initialState(r);selected=2;selectedDefect='F-03';candidateChoice=false;listFilter='전체';listStatus='전체';query='';go('login');}
function jumpTo(i){const j=journey[i];if(!j)return;$('#dialog').close();role=j[2];selected=2;selectedDefect='F-03';listFilter='전체';listStatus='전체';query='';state=initialState('agency');if(i>=8){state.evidence=true;state.field=true;state.captions['F-03']='[가상 예시] 옥상 난간 촬영 위치 기록입니다.';state.events.push('단계 예시: 현장자료 확인된 작업본');}if(i>=9)state.opinion=demoOpinion;if(i>=11){state.phase='shared';state.snapshots=[{version:1,opinion:demoOpinion,note:'최초 공유본',captions:{...state.captions}}];state.events.push('v1 결과 공유');}if(i>=15){state.request='[가상 보완 요청] F-03 옥상 난간 사진의 출입구 기준 위치 설명을 보완해 주세요.';state.phase='requested';state.events.push('v1의 F-03 보완 요청');}if(i>=17){state.reply='[가상 보완 답변] F-03-PHOTO-01은 옥상 출입구 우측 난간 구간입니다. 관찰 측정값은 변경하지 않았습니다.';state.phase='resubmitted';state.version=2;state.captions['F-03']=state.reply;state.snapshots.push({version:2,opinion:demoOpinion,note:state.reply,captions:{...state.captions}});state.events.push('v2 보완 결과 공유 · 기관 답변 완료');}if(i>=19&&i<=20){state.phase='complete';state.events.push('v2 결과 검토 완료 · 예시시');}if(i>=21)state=initialState('official');go(j[0]);toast('선택한 단계의 가상 상태를 불러왔습니다.');}
function renderViewer(){let handoff='';if(state.phase==='shared'&&role==='agency')handoff=btn('공무원 검토로 이어보기',"switchActor('official','review')",'primary');if(state.phase==='requested'&&role==='official')handoff=btn('기관 보완 응답으로 이어보기',"switchActor('agency','reply')",'primary');if(state.phase==='resubmitted'&&role==='agency')handoff=btn('공무원 재검토로 이어보기',"switchActor('official','review')",'primary');const isAuth=['login','first'].includes(screen);$('#viewer').innerHTML=`<div><strong>시안 검토 도구</strong> · ${isAuth?'로그인부터 체험할 수 있습니다.':`${role==='official'?'공무원':'전문기관'} 화면 · ${explanations[screen]?.[0]||'업무 건'}`}<br><span>가상 자료만 사용 · 새로고침하면 초기화 · 외부 통신·저장 없음</span></div><div class="actions">${isAuth?'':handoff}${btn('전체 화면 순서','showJourney()')}${btn('처음으로 초기화',"resetDemo('agency')")}</div>`;}

// The entry extension starts the viewer and adds public access and local demo restoration.
